import { researchDeterministicUuid } from './researchMetadataBuilder';
import { RESEARCH_GRANT_SOURCE_SEEDS } from './researchGrantSourceData';

// Demo seed records for the research objects. Mirrors how the bridge seeds the
// standard CRM (company/person/…) so a fresh local workspace opens with a
// coherent research team, live grant sources, and a few grants/opportunities to
// click through. Keys are object `nameSingular` to match the DataSource seed
// map. Relations are wired via `<field>Id` join columns pointing at parent
// record ids (see researchRelations.ts).

type SeedRecord = Record<string, unknown> & { id: string };

const ACTOR = {
  source: 'MANUAL',
  workspaceMemberId: null,
  name: 'Seed',
  context: null,
};

const SEED_TIMESTAMP = '2026-04-10T08:55:57.800Z';

// Stable id for a seed record, by object + key. Used both as a record's own id
// and as the join-column value on related records.
const recordId = (objectNameSingular: string, key: string): string =>
  researchDeterministicUuid(`research:record:${objectNameSingular}:${key}`);

const makeRecord = (
  objectNameSingular: string,
  key: string,
  position: number,
  fields: Record<string, unknown>,
): SeedRecord => ({
  id: recordId(objectNameSingular, key),
  createdAt: SEED_TIMESTAMP,
  updatedAt: SEED_TIMESTAMP,
  deletedAt: null,
  position,
  createdBy: ACTOR,
  updatedBy: ACTOR,
  ...fields,
});

const TEAM = recordId('researchTeam', 'quantum-materials-lab');
const RESEARCHER = {
  maya: recordId('researcher', 'maya-okafor'),
  liam: recordId('researcher', 'liam-tran'),
  sofia: recordId('researcher', 'sofia-reyes'),
  noah: recordId('researcher', 'noah-bell'),
};
const PROJECT = {
  topological: recordId('project', 'topological-insulators'),
  spintronic: recordId('project', 'spintronic-memory'),
  cryo: recordId('project', 'cryo-instrumentation'),
};
const GRANT = {
  nserc: recordId('grant', 'nserc-discovery'),
  innovate: recordId('grant', 'innovate-bc-ignite'),
};
const CYCLE = {
  fall: recordId('applicationCycle', 'fall-2026-tri-agency'),
  spring: recordId('applicationCycle', 'spring-2026-industry'),
};
const APP = {
  cihrTeam: recordId('grantApplication', 'cihr-team-app'),
  innovate: recordId('grantApplication', 'innovate-ignite-app'),
  mitacs: recordId('grantApplication', 'mitacs-app'),
  nsercRenewal: recordId('grantApplication', 'nserc-renewal-app'),
};
const SOURCE = (libraryKey: string) => recordId('grantSource', libraryKey);
const OPP = (key: string) => recordId('grantOpportunity', key);

// Manuscript authoring demo: the lab's topological-insulator paper, composed
// from sections + figures + references against a Nature-style journal template.
const MANUSCRIPT = recordId('manuscript', 'ti-qubit-substrates');
const JOURNAL = {
  nature: recordId('journalTemplate', 'nature'),
  ieee: recordId('journalTemplate', 'ieee-trans'),
  authorDate: recordId('journalTemplate', 'generic-author-date'),
};
const SECTION = (key: string) => recordId('manuscriptSection', key);

const grantSourceRecords = (): SeedRecord[] =>
  RESEARCH_GRANT_SOURCE_SEEDS.map((source, index) =>
    makeRecord('grantSource', source.libraryKey, index, {
      name: source.name,
      url: source.url,
      sourceType: source.sourceType,
      jurisdiction: source.jurisdiction,
      funderType: source.funderType,
      opportunityKind: source.opportunityKind ?? 'GRANT',
      topicTags: source.topicTags,
      eligibilityTags: source.eligibilityTags,
      scrapeCadence: source.scrapeCadence,
      trustLevel: source.trustLevel,
      status: source.status,
      lastScrapedAt: null,
      notes: source.notes,
    }),
  );

const researchTeamRecords = (): SeedRecord[] => [
  makeRecord('researchTeam', 'quantum-materials-lab', 0, {
    name: 'Quantum Materials Lab',
    principalInvestigator: 'Dr. Maya Okafor',
    institution: 'University of British Columbia',
    department: 'Department of Physics & Astronomy',
    focusAreas: ['quantum materials', 'spintronics', 'low-temperature physics'],
    individualMode: false,
    website: 'https://qml.example.ubc.ca',
    notes: 'Core lab workspace for the quantum materials group.',
  }),
];

const researcherRecords = (): SeedRecord[] => [
  makeRecord('researcher', 'maya-okafor', 0, {
    name: 'Dr. Maya Okafor',
    email: 'maya.okafor@example.ubc.ca',
    role: 'PI',
    teamId: TEAM,
    orcid: '0000-0002-1825-0097',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Principal investigator.',
  }),
  makeRecord('researcher', 'liam-tran', 1, {
    name: 'Liam Tran',
    email: 'liam.tran@example.ubc.ca',
    role: 'POSTDOC',
    teamId: TEAM,
    orcid: '0000-0001-7300-1234',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Leads the spintronics sub-project.',
  }),
  makeRecord('researcher', 'sofia-reyes', 2, {
    name: 'Sofia Reyes',
    email: 'sofia.reyes@example.ubc.ca',
    role: 'PHD',
    teamId: TEAM,
    orcid: '0000-0003-4444-9876',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Thesis on topological insulators.',
  }),
  makeRecord('researcher', 'noah-bell', 3, {
    name: 'Noah Bell',
    email: 'noah.bell@example.ubc.ca',
    role: 'RESEARCH_ASSISTANT',
    teamId: TEAM,
    orcid: '',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Sample fabrication and lab operations.',
  }),
];

const projectRecords = (): SeedRecord[] => [
  makeRecord('project', 'topological-insulators', 0, {
    name: 'Topological insulators for fault-tolerant qubits',
    leadId: RESEARCHER.sofia,
    teamId: TEAM,
    status: 'ACTIVE',
    fundingStatus: 'PARTIALLY_FUNDED',
    summary:
      'Growth and characterization of topological insulator thin films for robust qubit substrates.',
    startDate: '2025-09-01T00:00:00.000Z',
    endDate: '2028-08-31T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('project', 'spintronic-memory', 1, {
    name: 'Low-power spintronic memory devices',
    leadId: RESEARCHER.liam,
    teamId: TEAM,
    status: 'ACTIVE',
    fundingStatus: 'SEEKING',
    summary: 'Prototyping energy-efficient magnetic memory cells.',
    startDate: '2026-01-15T00:00:00.000Z',
    endDate: '2027-12-31T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('project', 'cryo-instrumentation', 2, {
    name: 'Shared cryogenic measurement platform',
    leadId: RESEARCHER.maya,
    teamId: TEAM,
    status: 'PLANNING',
    fundingStatus: 'UNFUNDED',
    summary: 'Infrastructure project for a shared dilution-refrigerator setup.',
    startDate: null,
    endDate: null,
    notes: 'Candidate for an infrastructure / equipment grant.',
  }),
];

const grantRecords = (): SeedRecord[] => [
  makeRecord('grant', 'nserc-discovery', 0, {
    name: 'Quantum materials core program',
    funder: 'Natural Sciences and Engineering Research Council',
    program: 'Discovery Grants',
    status: 'ACTIVE',
    priority: 'HIGH',
    projectId: PROJECT.topological,
    leadId: RESEARCHER.maya,
    amountRequested: 600000,
    amountAwarded: 540000,
    fitScore: 5,
    applicationDueDate: '2025-11-01T00:00:00.000Z',
    submittedAt: '2025-10-28T00:00:00.000Z',
    decisionAt: '2026-04-01T00:00:00.000Z',
    startDate: '2026-04-01T00:00:00.000Z',
    endDate: '2031-03-31T00:00:00.000Z',
    nextReportDue: '2026-12-31T00:00:00.000Z',
    opportunityUrl:
      'https://www.nserc-crsng.gc.ca/professors-professeurs/grants-subs/dgigp-psigp_eng.asp',
    nextAction: 'Prepare year-1 progress report',
    notes: '',
  }),
  makeRecord('grant', 'cihr-project', 1, {
    name: 'Quantum sensing for early diagnostics',
    funder: 'Canadian Institutes of Health Research',
    program: 'Project Grant',
    status: 'SUBMITTED',
    priority: 'HIGH',
    projectId: PROJECT.spintronic,
    leadId: RESEARCHER.liam,
    amountRequested: 450000,
    amountAwarded: null,
    fitScore: 3,
    applicationDueDate: '2026-03-03T00:00:00.000Z',
    submittedAt: '2026-03-01T00:00:00.000Z',
    decisionAt: null,
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl: 'https://www.researchnet-recherchenet.ca/',
    nextAction: 'Await notice of decision',
    notes: '',
  }),
  makeRecord('grant', 'innovate-bc-ignite', 2, {
    name: 'Spintronic memory commercialization',
    funder: 'Innovate BC',
    program: 'Ignite',
    status: 'DRAFTING',
    priority: 'MEDIUM',
    projectId: PROJECT.spintronic,
    opportunityId: OPP('innovate-bc-ignite-2026'),
    leadId: RESEARCHER.liam,
    amountRequested: 300000,
    amountAwarded: null,
    fitScore: 4,
    applicationDueDate: '2026-07-15T00:00:00.000Z',
    submittedAt: null,
    decisionAt: null,
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl: 'https://www.innovatebc.ca/',
    nextAction: 'Draft commercialization plan',
    notes: 'Requires an industry partner match.',
  }),
  makeRecord('grant', 'cfi-jelf', 3, {
    name: 'Shared cryogenic measurement platform',
    funder: 'Canada Foundation for Innovation',
    program: 'John R. Evans Leaders Fund',
    status: 'PROSPECTING',
    priority: 'MEDIUM',
    projectId: PROJECT.cryo,
    leadId: RESEARCHER.maya,
    amountRequested: 250000,
    amountAwarded: null,
    fitScore: 4,
    applicationDueDate: '2026-10-01T00:00:00.000Z',
    submittedAt: null,
    decisionAt: null,
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl: 'https://www.innovation.ca/',
    nextAction: 'Confirm institutional support',
    notes: '',
  }),
  makeRecord('grant', 'nfrf-exploration', 4, {
    name: 'Topological qubits feasibility study',
    funder: 'Tri-Agency (NFRF)',
    program: 'Exploration',
    status: 'DECLINED',
    priority: 'LOW',
    projectId: PROJECT.topological,
    leadId: RESEARCHER.sofia,
    amountRequested: 250000,
    amountAwarded: null,
    fitScore: 2,
    applicationDueDate: '2025-02-15T00:00:00.000Z',
    submittedAt: '2025-02-10T00:00:00.000Z',
    decisionAt: '2025-07-01T00:00:00.000Z',
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl:
      'https://www.sshrc-crsh.gc.ca/funding-financement/nfrf-fnfr/',
    nextAction: 'Revise and resubmit next cycle',
    notes: 'Reviewers wanted clearer interdisciplinary scope.',
  }),
];

const grantOpportunityRecords = (): SeedRecord[] => [
  makeRecord('grantOpportunity', 'cihr-team-grant', 0, {
    name: 'Quantum technologies for health',
    funder: 'Canadian Institutes of Health Research',
    program: 'Team Grant',
    opportunityKind: 'GRANT',
    sourceId: SOURCE('cihr-researchnet'),
    opportunityUrl: 'https://www.researchnet-recherchenet.ca/',
    applicationDueDate: '2026-09-15T00:00:00.000Z',
    registrationDueDate: '2026-07-01T00:00:00.000Z',
    amountText: 'Up to $1,500,000 over 5 years',
    fitScore: 4,
    confidence: 'HIGH',
    status: 'NEW',
    eligibility: 'Canadian institutions; interdisciplinary teams',
    topicTags: ['health', 'quantum', 'team'],
    description:
      'Funds interdisciplinary teams applying quantum technologies to health challenges.',
  }),
  makeRecord('grantOpportunity', 'innovate-bc-ignite-2026', 1, {
    name: 'Fall 2026 commercialization intake',
    funder: 'Innovate BC',
    program: 'Ignite',
    opportunityKind: 'GRANT',
    sourceId: SOURCE('innovate-bc'),
    opportunityUrl: 'https://www.innovatebc.ca/',
    applicationDueDate: '2026-07-15T00:00:00.000Z',
    registrationDueDate: null,
    amountText: 'Up to $300,000',
    fitScore: 5,
    confidence: 'HIGH',
    status: 'REVIEWING',
    eligibility: 'BC-based research with industry partner',
    topicTags: ['bc', 'commercialization', 'tech'],
    description:
      'Funds late-stage research with a clear path to commercialization.',
  }),
  makeRecord('grantOpportunity', 'ndit-grant-writing', 2, {
    name: 'Grant writing support reimbursement',
    funder: 'Northern Development Initiative Trust',
    program: 'Grant Writing Support',
    opportunityKind: 'GRANT',
    sourceId: SOURCE('northern-development-initiative-trust'),
    opportunityUrl: 'https://www.northerndevelopment.bc.ca/',
    applicationDueDate: null,
    registrationDueDate: null,
    amountText: 'Up to $2,500 (matching)',
    fitScore: 2,
    confidence: 'MEDIUM',
    status: 'NEW',
    eligibility: 'Northern BC organizations',
    topicTags: ['bc', 'capacity', 'matching'],
    description: 'Reimburses a portion of professional grant-writing costs.',
  }),
  makeRecord('grantOpportunity', 'nrc-collaboration', 3, {
    name: 'Collaborative R&D with NRC labs',
    funder: 'National Research Council Canada',
    program: 'Collaborative R&D',
    opportunityKind: 'GRANT',
    sourceId: SOURCE('nrc-research-collaboration'),
    opportunityUrl: 'https://nrc.canada.ca/',
    applicationDueDate: '2026-08-30T00:00:00.000Z',
    registrationDueDate: null,
    amountText: 'Negotiated',
    fitScore: 4,
    confidence: 'MEDIUM',
    status: 'NEW',
    eligibility: 'Canadian researchers partnering with NRC',
    topicTags: ['materials', 'collaboration'],
    description: 'Co-funded collaborative research with NRC laboratories.',
  }),
  makeRecord('grantOpportunity', 'mitacs-accelerate', 4, {
    name: 'Graduate internship with industry partner',
    funder: 'Mitacs',
    program: 'Accelerate',
    opportunityKind: 'FELLOWSHIP',
    sourceId: SOURCE('mitacs-accelerate-fellowships'),
    opportunityUrl: 'https://www.mitacs.ca/',
    applicationDueDate: null,
    registrationDueDate: null,
    amountText: '$15,000 per 4-month unit',
    fitScore: 3,
    confidence: 'HIGH',
    status: 'ACCEPTED',
    eligibility: 'Graduate students with industry partner',
    careerStage: 'ANY',
    eligibilityNotes:
      'Open to graduate students and postdocs at Canadian institutions; requires a partner organization that contributes matching funds.',
    relevanceVerdict: 'LIKELY',
    relevanceReason:
      'Good fit for the spintronics sub-project, which has an industry partner. You would need: a partner commitment letter and an intern.',
    topicTags: ['internship', 'students', 'partner'],
    description: 'Funds graduate internships co-supervised with industry.',
  }),
  makeRecord('grantOpportunity', 'first-nations-clean-energy', 5, {
    name: 'First Nations clean energy stream',
    funder: 'Province of British Columbia',
    program: 'Clean Energy Business Fund',
    opportunityKind: 'GRANT',
    sourceId: SOURCE('first-nations-clean-energy-business-fund'),
    opportunityUrl: 'https://www2.gov.bc.ca/',
    applicationDueDate: '2026-06-30T00:00:00.000Z',
    registrationDueDate: null,
    amountText: 'Varies',
    fitScore: 1,
    confidence: 'LOW',
    status: 'REJECTED',
    eligibility: 'First Nations communities and partnerships',
    careerStage: 'ANY',
    eligibilityNotes:
      'Restricted to First Nations communities and their business partnerships.',
    relevanceVerdict: 'INELIGIBLE',
    relevanceReason:
      'Out of scope: the lab is not an eligible applicant for this stream.',
    topicTags: ['energy', 'bc'],
    description: 'Out of scope for this lab — kept for completeness.',
  }),
  // Scholarships & fellowships — individual awards, gated on career stage and
  // citizenship so the eligibility assessment has something real to read.
  makeRecord('grantOpportunity', 'vanier-cgs-2026', 6, {
    name: 'Vanier Canada Graduate Scholarship 2026',
    funder: 'Government of Canada',
    program: 'Vanier CGS',
    opportunityKind: 'SCHOLARSHIP',
    sourceId: SOURCE('vanier-cgs'),
    opportunityUrl: 'https://vanier.gc.ca/',
    applicationDueDate: '2026-11-01T00:00:00.000Z',
    registrationDueDate: '2026-09-15T00:00:00.000Z',
    amountText: '$50,000 / year for 3 years',
    fitScore: 4,
    confidence: 'HIGH',
    status: 'NEW',
    eligibility: 'Doctoral students; nominated by the institution',
    careerStage: 'DOCTORAL',
    eligibilityNotes:
      'Open to Canadian and international doctoral students who demonstrate leadership and high scholarly achievement. Candidates must be nominated by their institution.',
    relevanceVerdict: 'ELIGIBLE',
    relevanceReason:
      'Strong fit for Sofia (doctoral). You would need: an institutional nomination, transcripts, and reference letters.',
    topicTags: ['doctoral', 'leadership', 'quantum'],
    description:
      'Prestigious doctoral scholarship for students with leadership and research excellence.',
  }),
  makeRecord('grantOpportunity', 'nserc-cgs-d-2026', 7, {
    name: 'NSERC CGS-D Doctoral Scholarship',
    funder: 'Natural Sciences and Engineering Research Council',
    program: 'CGS-D',
    opportunityKind: 'SCHOLARSHIP',
    sourceId: SOURCE('nserc-pgs-cgs'),
    opportunityUrl: 'https://www.nserc-crsng.gc.ca/',
    applicationDueDate: '2026-10-01T00:00:00.000Z',
    registrationDueDate: null,
    amountText: '$35,000 / year for 3 years',
    fitScore: 5,
    confidence: 'HIGH',
    status: 'NEW',
    eligibility: 'Doctoral students in natural sciences or engineering',
    careerStage: 'DOCTORAL',
    eligibilityNotes:
      'Restricted to Canadian citizens and permanent residents enrolled in an eligible doctoral program in the natural sciences or engineering.',
    relevanceVerdict: 'ELIGIBLE',
    relevanceReason:
      'Excellent fit for a physics doctoral student. You would need: transcripts, two references, and an outline of proposed research.',
    topicTags: ['doctoral', 'physics', 'materials'],
    description:
      'Federal doctoral scholarship in the natural sciences and engineering.',
  }),
  makeRecord('grantOpportunity', 'banting-postdoc-2026', 8, {
    name: 'Banting Postdoctoral Fellowship',
    funder: 'Government of Canada',
    program: 'Banting',
    opportunityKind: 'FELLOWSHIP',
    sourceId: SOURCE('banting-postdoctoral'),
    opportunityUrl: 'https://banting.fellowships-bourses.gc.ca/',
    applicationDueDate: '2026-09-20T00:00:00.000Z',
    registrationDueDate: null,
    amountText: '$70,000 / year for 2 years',
    fitScore: 4,
    confidence: 'MEDIUM',
    status: 'NEW',
    eligibility: 'Postdoctoral researchers; nominated by host institution',
    careerStage: 'POSTDOCTORAL',
    eligibilityNotes:
      'Open to Canadian and international postdoctoral researchers within a few years of completing their PhD. Nominated by the host institution.',
    relevanceVerdict: 'UNKNOWN',
    relevanceReason:
      'Topically strong, but the lab currently has no eligible postdoc to nominate. Revisit if Liam transitions to a postdoctoral appointment.',
    topicTags: ['postdoctoral', 'research-leadership', 'quantum'],
    description: 'Elite postdoctoral fellowship for emerging research leaders.',
  }),
];

const applicationCycleRecords = (): SeedRecord[] => [
  makeRecord('applicationCycle', 'fall-2026-tri-agency', 0, {
    name: 'Fall 2026 Tri-Agency push',
    status: 'OPEN',
    openDate: '2026-06-01T00:00:00.000Z',
    closeDate: '2026-09-15T00:00:00.000Z',
    focus: 'Quantum materials and sensing — flagship proposals',
    owner: 'Dr. Maya Okafor',
    description:
      'Coordinated submission window for NSERC/CIHR/NFRF aligned with the lab’s strategic needs.',
  }),
  makeRecord('applicationCycle', 'spring-2026-industry', 1, {
    name: 'Spring 2026 industry partnerships',
    status: 'REVIEWING',
    openDate: '2026-01-10T00:00:00.000Z',
    closeDate: '2026-04-30T00:00:00.000Z',
    focus: 'Commercialization and matched-funding opportunities',
    owner: 'Liam Tran',
    description: 'Innovate BC / Mitacs partnership-driven applications.',
  }),
];

const grantApplicationRecords = (): SeedRecord[] => [
  makeRecord('grantApplication', 'cihr-team-app', 0, {
    name: 'Quantum sensing platform for early diagnostics',
    applicantId: RESEARCHER.maya,
    organization: 'Quantum Materials Lab',
    email: 'maya.okafor@example.ubc.ca',
    grantId: null,
    projectId: PROJECT.spintronic,
    opportunityId: OPP('cihr-team-grant'),
    cycleId: CYCLE.fall,
    amountRequested: 1500000,
    projectSummary:
      'Interdisciplinary team proposal for quantum-enabled diagnostics.',
    status: 'REVIEWING',
    source: 'ADMIN',
    submittedAt: '2026-06-20T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('grantApplication', 'innovate-ignite-app', 1, {
    name: 'Spintronic memory commercialization',
    applicantId: RESEARCHER.liam,
    organization: 'Quantum Materials Lab',
    email: 'liam.tran@example.ubc.ca',
    grantId: GRANT.innovate,
    projectId: PROJECT.spintronic,
    opportunityId: OPP('innovate-bc-ignite-2026'),
    cycleId: CYCLE.spring,
    amountRequested: 300000,
    projectSummary: 'Late-stage development with a hardware partner.',
    status: 'SHORTLISTED',
    source: 'PORTAL',
    submittedAt: '2026-04-15T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('grantApplication', 'mitacs-app', 2, {
    name: 'Graduate internship — topological thin films',
    applicantId: RESEARCHER.sofia,
    organization: 'Quantum Materials Lab',
    email: 'sofia.reyes@example.ubc.ca',
    grantId: null,
    projectId: PROJECT.topological,
    opportunityId: OPP('mitacs-accelerate'),
    cycleId: CYCLE.spring,
    amountRequested: 60000,
    projectSummary:
      'Four internship units co-supervised with an industry partner.',
    status: 'APPROVED',
    source: 'PORTAL',
    submittedAt: '2026-02-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('grantApplication', 'nserc-renewal-app', 3, {
    name: 'Discovery program renewal',
    applicantId: RESEARCHER.maya,
    organization: 'Quantum Materials Lab',
    email: 'maya.okafor@example.ubc.ca',
    grantId: GRANT.nserc,
    projectId: PROJECT.topological,
    opportunityId: null,
    cycleId: CYCLE.fall,
    amountRequested: 600000,
    projectSummary: 'Renewal of the lab’s flagship Discovery program.',
    status: 'SUBMITTED',
    source: 'ADMIN',
    submittedAt: '2026-06-18T00:00:00.000Z',
    notes: '',
  }),
];

const milestoneRecords = (): SeedRecord[] => [
  makeRecord('milestone', 'ti-film-growth', 0, {
    name: 'Achieve reproducible TI thin-film growth',
    projectId: PROJECT.topological,
    ownerId: RESEARCHER.sofia,
    status: 'IN_PROGRESS',
    dueDate: '2026-09-30T00:00:00.000Z',
    progress: 60,
    notes: '',
  }),
  makeRecord('milestone', 'spintronic-prototype', 1, {
    name: 'First spintronic memory prototype',
    projectId: PROJECT.spintronic,
    ownerId: RESEARCHER.liam,
    status: 'NOT_STARTED',
    dueDate: '2026-12-15T00:00:00.000Z',
    progress: 0,
    notes: '',
  }),
  makeRecord('milestone', 'cryo-procurement', 2, {
    name: 'Dilution refrigerator procurement',
    projectId: PROJECT.cryo,
    ownerId: RESEARCHER.maya,
    status: 'BLOCKED',
    dueDate: '2026-11-01T00:00:00.000Z',
    progress: 10,
    notes: 'Blocked on infrastructure funding.',
  }),
  makeRecord('milestone', 'year1-report', 3, {
    name: 'NSERC year-1 progress report',
    projectId: PROJECT.topological,
    ownerId: RESEARCHER.maya,
    status: 'IN_PROGRESS',
    dueDate: '2026-12-31T00:00:00.000Z',
    progress: 25,
    notes: '',
  }),
  makeRecord('milestone', 'sample-pipeline', 4, {
    name: 'Standardize sample fabrication pipeline',
    projectId: PROJECT.spintronic,
    ownerId: RESEARCHER.noah,
    status: 'DONE',
    dueDate: '2026-03-31T00:00:00.000Z',
    progress: 100,
    notes: '',
  }),
];

const datasetRecords = (): SeedRecord[] => [
  makeRecord('dataset', 'arpes-spectra', 0, {
    name: 'ARPES spectra — TI thin films',
    projectId: PROJECT.topological,
    dataType: 'IMAGING',
    status: 'ANALYSIS',
    storageLocation: 'Lab NAS / arpes/2026',
    sizeGb: 420,
    hasEthicsApproval: false,
    collectedAt: '2026-05-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('dataset', 'transport-measurements', 1, {
    name: 'Magnetotransport measurements',
    projectId: PROJECT.spintronic,
    dataType: 'TABULAR',
    status: 'COLLECTING',
    storageLocation: 'Lab NAS / transport/2026',
    sizeGb: 35,
    hasEthicsApproval: false,
    collectedAt: '2026-06-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('dataset', 'fabrication-logs', 2, {
    name: 'Sample fabrication logbook',
    projectId: PROJECT.spintronic,
    dataType: 'TEXT',
    status: 'COLLECTING',
    storageLocation: 'Electronic lab notebook',
    sizeGb: 1,
    hasEthicsApproval: false,
    collectedAt: '2026-01-15T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('dataset', 'dft-simulations', 3, {
    name: 'DFT simulation outputs',
    projectId: PROJECT.topological,
    dataType: 'OTHER',
    status: 'ARCHIVED',
    storageLocation: 'Compute cluster / scratch archived to NAS',
    sizeGb: 180,
    hasEthicsApproval: false,
    collectedAt: '2025-12-01T00:00:00.000Z',
    notes: '',
  }),
];

const manuscriptRecords = (): SeedRecord[] => [
  makeRecord('manuscript', 'ti-qubit-substrates', 0, {
    name: 'Topological insulator substrates for robust qubits',
    projectId: PROJECT.topological,
    leadAuthorId: RESEARCHER.sofia,
    targetJournalId: JOURNAL.nature,
    manuscriptType: 'JOURNAL_PAPER',
    status: 'DRAFTING',
    targetVenue: 'Nature Materials',
    progress: 40,
    targetDate: '2026-11-30T00:00:00.000Z',
    doi: '',
    notes: '',
  }),
  makeRecord('manuscript', 'reyes-thesis', 1, {
    name: 'PhD thesis — Topological materials for quantum computing',
    projectId: PROJECT.topological,
    leadAuthorId: RESEARCHER.sofia,
    manuscriptType: 'THESIS',
    status: 'OUTLINE',
    targetVenue: 'UBC',
    progress: 15,
    targetDate: '2028-06-30T00:00:00.000Z',
    doi: '',
    notes: '',
  }),
  makeRecord('manuscript', 'spintronic-preprint', 2, {
    name: 'Energy-efficient spintronic memory: a preprint',
    projectId: PROJECT.spintronic,
    leadAuthorId: RESEARCHER.liam,
    manuscriptType: 'PREPRINT',
    status: 'SUBMITTED',
    targetVenue: 'arXiv',
    progress: 90,
    targetDate: '2026-07-31T00:00:00.000Z',
    doi: '10.48550/arXiv.2606.00000',
    notes: '',
  }),
  makeRecord('manuscript', 'cryo-methods', 3, {
    name: 'A shared cryogenic measurement platform (methods)',
    projectId: PROJECT.cryo,
    leadAuthorId: RESEARCHER.maya,
    manuscriptType: 'CONFERENCE_PAPER',
    status: 'INTERNAL_REVIEW',
    targetVenue: 'APS March Meeting',
    progress: 70,
    targetDate: '2026-10-01T00:00:00.000Z',
    doi: '',
    notes: '',
  }),
];

const applicationRequirementRecords = (): SeedRecord[] => [
  // CIHR Team Grant application checklist
  makeRecord('applicationRequirement', 'cihr-narrative', 0, {
    name: 'Research narrative (10 pages)',
    applicationId: APP.cihrTeam,
    category: 'NARRATIVE',
    status: 'READY',
    dueDate: '2026-09-01T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'cihr-budget', 1, {
    name: 'Budget and justification',
    applicationId: APP.cihrTeam,
    category: 'BUDGET',
    status: 'NEEDED',
    dueDate: '2026-09-05T00:00:00.000Z',
    formNumber: '',
    notes: 'Coordinate with finance office.',
  }),
  makeRecord('applicationRequirement', 'cihr-ccv', 2, {
    name: 'Common CV for all team members',
    applicationId: APP.cihrTeam,
    category: 'CV',
    status: 'REQUESTED',
    dueDate: '2026-09-01T00:00:00.000Z',
    formNumber: 'CCV',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'cihr-ethics', 3, {
    name: 'Ethics approval (REB)',
    applicationId: APP.cihrTeam,
    category: 'ETHICS',
    status: 'NEEDED',
    dueDate: '2026-09-10T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  // Innovate BC Ignite checklist
  makeRecord('applicationRequirement', 'ignite-commercialization', 4, {
    name: 'Commercialization plan',
    applicationId: APP.innovate,
    category: 'NARRATIVE',
    status: 'READY',
    dueDate: '2026-07-10T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'ignite-partner-letter', 5, {
    name: 'Industry partner letter of support',
    applicationId: APP.innovate,
    category: 'LETTER_OF_SUPPORT',
    status: 'ATTACHED',
    dueDate: '2026-07-01T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'ignite-budget', 6, {
    name: 'Matched-funding budget',
    applicationId: APP.innovate,
    category: 'BUDGET',
    status: 'READY',
    dueDate: '2026-07-10T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  // Mitacs internship checklist
  makeRecord('applicationRequirement', 'mitacs-proposal', 7, {
    name: 'Internship research proposal',
    applicationId: APP.mitacs,
    category: 'NARRATIVE',
    status: 'ATTACHED',
    dueDate: '2026-01-25T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'mitacs-partner-form', 8, {
    name: 'Partner organization form',
    applicationId: APP.mitacs,
    category: 'FORM',
    status: 'ATTACHED',
    dueDate: '2026-01-25T00:00:00.000Z',
    formNumber: 'MITACS-PO',
    notes: '',
  }),
  // NSERC Discovery renewal checklist
  makeRecord('applicationRequirement', 'nserc-proposal', 9, {
    name: 'Discovery proposal (5 pages)',
    applicationId: APP.nsercRenewal,
    category: 'NARRATIVE',
    status: 'READY',
    dueDate: '2026-06-15T00:00:00.000Z',
    formNumber: 'Form 101',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'nserc-ccv', 10, {
    name: 'NSERC CCV',
    applicationId: APP.nsercRenewal,
    category: 'CV',
    status: 'ATTACHED',
    dueDate: '2026-06-10T00:00:00.000Z',
    formNumber: 'CCV',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'nserc-hqp', 11, {
    name: 'HQP training plan',
    applicationId: APP.nsercRenewal,
    category: 'OTHER',
    status: 'REQUESTED',
    dueDate: '2026-06-15T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
];

const applicantProfileRecords = (): SeedRecord[] => [
  makeRecord('applicantProfile', 'maya-okafor-profile', 0, {
    name: 'Maya Okafor — applicant profile',
    researcherId: RESEARCHER.maya,
    fullName: 'Dr. Maya Okafor',
    email: 'maya.okafor@example.ubc.ca',
    phone: '+1 604 555 0142',
    orcid: '0000-0002-1825-0097',
    careerStage: 'ESTABLISHED',
    citizenship: 'Canadian',
    residency: 'British Columbia, Canada',
    institution: 'University of British Columbia',
    department: 'Department of Physics & Astronomy',
    discipline: 'Condensed-matter physics',
    keywords: ['quantum materials', 'spintronics', 'low-temperature physics'],
    addressLine1: '6224 Agricultural Road',
    city: 'Vancouver',
    province: 'British Columbia',
    postalCode: 'V6T 1Z1',
    country: 'Canada',
    bioShort:
      'PI of the Quantum Materials Lab at UBC, working on topological and spintronic materials for quantum technologies.',
    bioLong: '',
    notes: 'Default profile used for autofill and application drafting.',
  }),
  makeRecord('applicantProfile', 'sofia-reyes-profile', 1, {
    name: 'Sofia Reyes — applicant profile',
    researcherId: RESEARCHER.sofia,
    fullName: 'Sofia Reyes',
    email: 'sofia.reyes@example.ubc.ca',
    phone: '',
    orcid: '0000-0003-4444-9876',
    careerStage: 'DOCTORAL',
    citizenship: 'Canadian',
    residency: 'British Columbia, Canada',
    institution: 'University of British Columbia',
    department: 'Department of Physics & Astronomy',
    discipline: 'Quantum materials',
    keywords: ['topological insulators', 'thin films', 'qubits'],
    addressLine1: '',
    city: 'Vancouver',
    province: 'British Columbia',
    postalCode: '',
    country: 'Canada',
    bioShort:
      'PhD candidate studying topological insulator thin films for fault-tolerant qubits.',
    bioLong: '',
    notes: 'Eligible for doctoral scholarships (Vanier, NSERC CGS-D).',
  }),
];

const applicationSectionRecords = (): SeedRecord[] => [
  // CIHR Team Grant application — partially drafted narrative.
  makeRecord('applicationSection', 'cihr-abstract', 0, {
    name: 'Abstract',
    applicationId: APP.cihrTeam,
    sectionType: 'ABSTRACT',
    status: 'FINAL',
    prompt: 'Summarize the proposed research in 250 words.',
    content:
      'We propose an interdisciplinary program applying quantum-sensing techniques developed for materials research to early disease diagnostics, pairing physicists with clinical collaborators to translate sensitivity gains into point-of-care assays.',
    wordLimit: 250,
    wordCount: 42,
    reusedFromId: '',
    notes: '',
  }),
  makeRecord('applicationSection', 'cihr-lay-summary', 1, {
    name: 'Lay summary',
    applicationId: APP.cihrTeam,
    sectionType: 'LAY_SUMMARY',
    status: 'DRAFTING',
    prompt: 'Describe the project for a non-specialist audience.',
    content:
      'Tiny quantum sensors can detect faint magnetic signals. We want to use them to spot disease markers earlier and more cheaply than today’s tests.',
    wordLimit: 200,
    wordCount: 27,
    reusedFromId: '',
    notes: '',
  }),
  makeRecord('applicationSection', 'cihr-impact', 2, {
    name: 'Impact & significance',
    applicationId: APP.cihrTeam,
    sectionType: 'IMPACT',
    status: 'NOT_STARTED',
    prompt: 'What is the expected health and societal impact?',
    content: '',
    wordLimit: 750,
    wordCount: 0,
    reusedFromId: '',
    notes:
      'Reuse the impact answer from the spintronics project as a starting point.',
  }),
  makeRecord('applicationSection', 'cihr-budget-justification', 3, {
    name: 'Budget justification',
    applicationId: APP.cihrTeam,
    sectionType: 'BUDGET_JUSTIFICATION',
    status: 'DRAFTING',
    prompt: 'Justify each budget line.',
    content: '',
    wordLimit: 1000,
    wordCount: 0,
    reusedFromId: '',
    notes: '',
  }),
  // Innovate BC Ignite — commercialization-focused.
  makeRecord('applicationSection', 'ignite-summary', 4, {
    name: 'Commercialization summary',
    applicationId: APP.innovate,
    sectionType: 'LAY_SUMMARY',
    status: 'FINAL',
    prompt: 'Summarize the commercialization opportunity.',
    content:
      'Low-power spintronic memory cells promise large energy savings for edge devices. With a hardware partner we will validate a manufacturable prototype.',
    wordLimit: 300,
    wordCount: 24,
    reusedFromId: '',
    notes: '',
  }),
  makeRecord('applicationSection', 'ignite-impact', 5, {
    name: 'Economic impact',
    applicationId: APP.innovate,
    sectionType: 'IMPACT',
    status: 'IN_REVIEW',
    prompt: 'Describe the economic impact for British Columbia.',
    content:
      'Commercializing this technology in BC supports highly-qualified jobs and positions the province in the growing low-power memory market.',
    wordLimit: 500,
    wordCount: 21,
    reusedFromId: '',
    notes: '',
  }),
];

const reusableAnswerRecords = (): SeedRecord[] => [
  makeRecord('reusableAnswer', 'impact-spintronics', 0, {
    name: 'Impact — energy-efficient computing',
    questionType: 'IMPACT',
    projectId: PROJECT.spintronic,
    authorId: RESEARCHER.liam,
    funder: '',
    content:
      'Computing’s energy footprint is growing unsustainably. By reducing the energy per memory operation by an order of magnitude, this work addresses a key bottleneck for edge AI and data-centre efficiency, with direct environmental and economic benefits.',
    tags: ['energy', 'computing', 'sustainability'],
    wordCount: 41,
    timesUsed: 3,
    lastUsedAt: '2026-04-15T00:00:00.000Z',
    notes:
      'Strong general-purpose impact paragraph; adapt the framing per funder.',
  }),
  makeRecord('reusableAnswer', 'lay-summary-topological', 1, {
    name: 'Lay summary — topological qubits',
    questionType: 'LAY_SUMMARY',
    projectId: PROJECT.topological,
    authorId: RESEARCHER.sofia,
    funder: '',
    content:
      'Quantum computers are powerful but fragile. We grow special materials — topological insulators — that could protect quantum information from errors, making future quantum computers far more reliable.',
    tags: ['quantum', 'qubits', 'plain-language'],
    wordCount: 30,
    timesUsed: 2,
    lastUsedAt: '2026-03-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('reusableAnswer', 'budget-justification-tri-agency', 2, {
    name: 'Budget justification — Tri-Agency template',
    questionType: 'BUDGET_JUSTIFICATION',
    projectId: null,
    authorId: RESEARCHER.maya,
    funder: 'Natural Sciences and Engineering Research Council',
    content:
      'Personnel: one PhD student (stipend per institutional rates) and a part-time research assistant for sample fabrication. Equipment: consumables for thin-film growth and cryogenic measurement. Travel: one conference per year to disseminate results. Each line is essential to the proposed objectives.',
    tags: ['budget', 'tri-agency', 'personnel'],
    wordCount: 45,
    timesUsed: 4,
    lastUsedAt: '2026-05-20T00:00:00.000Z',
    notes: 'Reusable across NSERC/CIHR with minor edits.',
  }),
  makeRecord('reusableAnswer', 'pi-bio-okafor', 3, {
    name: 'PI biography — Okafor',
    questionType: 'BIO',
    projectId: null,
    authorId: RESEARCHER.maya,
    funder: '',
    content:
      'Dr. Maya Okafor is an Associate Professor of Physics at UBC. Her lab studies quantum materials for next-generation computing, with funding from NSERC and CFI and publications in Nature Materials and Physical Review Letters.',
    tags: ['bio', 'pi'],
    wordCount: 35,
    timesUsed: 6,
    lastUsedAt: '2026-06-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('reusableAnswer', 'edi-statement-lab', 4, {
    name: 'EDI statement — lab approach',
    questionType: 'EDI',
    projectId: null,
    authorId: RESEARCHER.maya,
    funder: '',
    content:
      'Our lab is committed to equity, diversity and inclusion: we recruit through inclusive practices, support trainees from underrepresented groups via mentorship, and design fieldwork and lab schedules to accommodate caregiving responsibilities.',
    tags: ['edi', 'inclusion', 'mentorship'],
    wordCount: 32,
    timesUsed: 5,
    lastUsedAt: '2026-05-10T00:00:00.000Z',
    notes: 'Most funders now require an EDI statement — keep this current.',
  }),
  makeRecord('reusableAnswer', 'methodology-thin-films', 5, {
    name: 'Methodology — thin-film growth & characterization',
    questionType: 'METHODOLOGY',
    projectId: PROJECT.topological,
    authorId: RESEARCHER.sofia,
    funder: '',
    content:
      'Films are grown by molecular-beam epitaxy and characterized by ARPES, X-ray diffraction, and magnetotransport. Growth parameters are iterated against measured band structure to optimize topological surface states.',
    tags: ['methodology', 'mbe', 'arpes'],
    wordCount: 29,
    timesUsed: 2,
    lastUsedAt: '2026-04-02T00:00:00.000Z',
    notes: '',
  }),
];

const journalTemplateRecords = (): SeedRecord[] => [
  makeRecord('journalTemplate', 'nature', 0, {
    name: 'Nature (numeric, superscript)',
    citationMode: 'NUMERIC_SUPERSCRIPT',
    citationStyleId: 'nature',
    figureLabelFormat: 'Figure {n}',
    tableLabelFormat: 'Table {n}',
    supplementPrefix: 'S',
    numberingScope: 'CONTINUOUS',
    crossRefFormat: 'Fig. {n}',
    figureCaptionPosition: 'BELOW',
    tableCaptionPosition: 'ABOVE',
    abstractWordLimit: 150,
    twoColumn: false,
    referenceDocUrl: '',
    outputFormats: ['DOCX', 'PDF', 'JATS'],
    notes: 'Superscript numeric citations; 150-word abstract.',
  }),
  makeRecord('journalTemplate', 'ieee-trans', 1, {
    name: 'IEEE Transactions',
    citationMode: 'NUMERIC',
    citationStyleId: 'ieee',
    figureLabelFormat: 'Fig. {n}',
    tableLabelFormat: 'TABLE {n}',
    supplementPrefix: 'S',
    numberingScope: 'CONTINUOUS',
    crossRefFormat: 'Fig. {n}',
    figureCaptionPosition: 'BELOW',
    tableCaptionPosition: 'ABOVE',
    abstractWordLimit: 250,
    twoColumn: true,
    referenceDocUrl: '',
    outputFormats: ['DOCX', 'PDF', 'LATEX'],
    notes: 'Two-column; bracketed numeric citations.',
  }),
  makeRecord('journalTemplate', 'generic-author-date', 2, {
    name: 'Generic (author–date)',
    citationMode: 'AUTHOR_DATE',
    citationStyleId: 'apa',
    figureLabelFormat: 'Figure {n}',
    tableLabelFormat: 'Table {n}',
    supplementPrefix: 'S',
    numberingScope: 'CONTINUOUS',
    crossRefFormat: 'Figure {n}',
    figureCaptionPosition: 'BELOW',
    tableCaptionPosition: 'ABOVE',
    abstractWordLimit: 250,
    twoColumn: false,
    referenceDocUrl: '',
    outputFormats: ['DOCX', 'PDF'],
    notes: 'Author–date in-text citations.',
  }),
];

// A reference as both flat fields (for the table) and the CSL-JSON blob (the
// source of truth the exporter uses).
const csl = (item: Record<string, unknown>): string => JSON.stringify(item);

const referenceRecords = (): SeedRecord[] => [
  makeRecord('reference', 'hasan2010', 0, {
    name: 'Colloquium: Topological insulators',
    citationKey: 'hasan2010',
    cslType: 'ARTICLE_JOURNAL',
    authors: 'Hasan, M. Z.; Kane, C. L.',
    year: 2010,
    containerTitle: 'Reviews of Modern Physics',
    volume: '82',
    issue: '4',
    pages: '3045–3067',
    doi: '10.1103/RevModPhys.82.3045',
    url: '',
    manuscriptId: MANUSCRIPT,
    projectId: PROJECT.topological,
    zoteroKey: '',
    cslJson: csl({
      id: 'hasan2010',
      type: 'article-journal',
      title: 'Colloquium: Topological insulators',
      author: [
        { family: 'Hasan', given: 'M. Z.' },
        { family: 'Kane', given: 'C. L.' },
      ],
      issued: { 'date-parts': [[2010]] },
      'container-title': 'Reviews of Modern Physics',
      volume: '82',
      page: '3045-3067',
      DOI: '10.1103/RevModPhys.82.3045',
    }),
    notes: '',
  }),
  makeRecord('reference', 'qi2011', 1, {
    name: 'Topological insulators and superconductors',
    citationKey: 'qi2011',
    cslType: 'ARTICLE_JOURNAL',
    authors: 'Qi, X.-L.; Zhang, S.-C.',
    year: 2011,
    containerTitle: 'Reviews of Modern Physics',
    volume: '83',
    issue: '4',
    pages: '1057–1110',
    doi: '10.1103/RevModPhys.83.1057',
    url: '',
    manuscriptId: MANUSCRIPT,
    projectId: PROJECT.topological,
    zoteroKey: '',
    cslJson: csl({
      id: 'qi2011',
      type: 'article-journal',
      title: 'Topological insulators and superconductors',
      author: [
        { family: 'Qi', given: 'X.-L.' },
        { family: 'Zhang', given: 'S.-C.' },
      ],
      issued: { 'date-parts': [[2011]] },
      'container-title': 'Reviews of Modern Physics',
      volume: '83',
      page: '1057-1110',
      DOI: '10.1103/RevModPhys.83.1057',
    }),
    notes: '',
  }),
  makeRecord('reference', 'chen2009', 2, {
    name: 'Experimental realization of a three-dimensional topological insulator',
    citationKey: 'chen2009',
    cslType: 'ARTICLE_JOURNAL',
    authors: 'Chen, Y. L.; et al.',
    year: 2009,
    containerTitle: 'Science',
    volume: '325',
    issue: '5937',
    pages: '178–181',
    doi: '10.1126/science.1173034',
    url: '',
    manuscriptId: MANUSCRIPT,
    projectId: PROJECT.topological,
    zoteroKey: '',
    cslJson: csl({
      id: 'chen2009',
      type: 'article-journal',
      title:
        'Experimental realization of a three-dimensional topological insulator, Bi2Te3',
      author: [{ family: 'Chen', given: 'Y. L.' }],
      issued: { 'date-parts': [[2009]] },
      'container-title': 'Science',
      volume: '325',
      page: '178-181',
      DOI: '10.1126/science.1173034',
    }),
    notes: '',
  }),
  makeRecord('reference', 'moore2010', 3, {
    name: 'The birth of topological insulators',
    citationKey: 'moore2010',
    cslType: 'ARTICLE_JOURNAL',
    authors: 'Moore, J. E.',
    year: 2010,
    containerTitle: 'Nature',
    volume: '464',
    issue: '7286',
    pages: '194–198',
    doi: '10.1038/nature08916',
    url: '',
    manuscriptId: MANUSCRIPT,
    projectId: PROJECT.topological,
    zoteroKey: '',
    cslJson: csl({
      id: 'moore2010',
      type: 'article-journal',
      title: 'The birth of topological insulators',
      author: [{ family: 'Moore', given: 'J. E.' }],
      issued: { 'date-parts': [[2010]] },
      'container-title': 'Nature',
      volume: '464',
      page: '194-198',
      DOI: '10.1038/nature08916',
    }),
    notes: '',
  }),
  makeRecord('reference', 'reyes2025', 4, {
    name: 'Reproducible MBE growth of topological insulator thin films',
    citationKey: 'reyes2025',
    cslType: 'PREPRINT',
    authors: 'Reyes, S.; Okafor, M.',
    year: 2025,
    containerTitle: 'arXiv',
    volume: '',
    issue: '',
    pages: '',
    doi: '10.48550/arXiv.2505.00000',
    url: 'https://arxiv.org/abs/2505.00000',
    manuscriptId: MANUSCRIPT,
    projectId: PROJECT.topological,
    zoteroKey: '',
    cslJson: csl({
      id: 'reyes2025',
      type: 'article',
      title: 'Reproducible MBE growth of topological insulator thin films',
      author: [
        { family: 'Reyes', given: 'S.' },
        { family: 'Okafor', given: 'M.' },
      ],
      issued: { 'date-parts': [[2025]] },
      'container-title': 'arXiv',
      DOI: '10.48550/arXiv.2505.00000',
      URL: 'https://arxiv.org/abs/2505.00000',
    }),
    notes: 'The lab’s own growth methods preprint.',
  }),
];

const manuscriptSectionRecords = (): SeedRecord[] => [
  makeRecord('manuscriptSection', 'ti-abstract', 0, {
    name: 'Abstract',
    manuscriptId: MANUSCRIPT,
    sectionType: 'ABSTRACT',
    placement: 'FRONT_MATTER',
    orderIndex: 0,
    status: 'FINAL',
    wordLimit: 150,
    wordCount: 58,
    includeInExport: true,
    content:
      'Topological insulators host symmetry-protected surface states that are robust against disorder, making them promising substrates for fault-tolerant qubits. Here we report reproducible molecular-beam-epitaxy growth of high-quality topological insulator thin films and characterize their surface band structure, demonstrating the clean, gapless Dirac cone required for qubit protection.',
    notes: '',
  }),
  makeRecord('manuscriptSection', 'ti-intro', 1, {
    name: 'Introduction',
    manuscriptId: MANUSCRIPT,
    sectionType: 'INTRODUCTION',
    placement: 'MAIN',
    orderIndex: 1,
    status: 'DRAFTING',
    wordLimit: 800,
    wordCount: 70,
    includeInExport: true,
    content:
      'Topological insulators are a class of quantum materials whose insulating bulk coexists with conducting, spin-momentum-locked surface states [@hasan2010; @qi2011]. Their surface states are protected by time-reversal symmetry, suggesting a route to robust quantum information substrates. The characteristic Dirac-cone band structure is sketched in [#fig:bandstructure]. In this work we focus on reproducible growth and surface characterization.',
    notes: '',
  }),
  makeRecord('manuscriptSection', 'ti-methods', 2, {
    name: 'Methods',
    manuscriptId: MANUSCRIPT,
    sectionType: 'METHODS',
    placement: 'MAIN',
    orderIndex: 2,
    status: 'DRAFTING',
    wordLimit: 1500,
    wordCount: 44,
    includeInExport: true,
    content:
      'Films were grown by molecular-beam epitaxy following our established protocol [@reyes2025]. Growth parameters are summarized in [#tab:growth]. Surface band structure was measured by angle-resolved photoemission spectroscopy (ARPES) at 15 K.',
    notes: '',
  }),
  makeRecord('manuscriptSection', 'ti-results', 3, {
    name: 'Results',
    manuscriptId: MANUSCRIPT,
    sectionType: 'RESULTS',
    placement: 'MAIN',
    orderIndex: 3,
    status: 'DRAFTING',
    wordLimit: 1500,
    wordCount: 52,
    includeInExport: true,
    content:
      'ARPES reveals a single, sharp Dirac cone at the Γ point ([#fig:arpes]), consistent with a topologically protected surface state and in agreement with prior reports on three-dimensional topological insulators [@chen2009]. The Dirac point sits within the bulk gap, indicating well-controlled bulk doping.',
    notes: '',
  }),
  makeRecord('manuscriptSection', 'ti-discussion', 4, {
    name: 'Discussion',
    manuscriptId: MANUSCRIPT,
    sectionType: 'DISCUSSION',
    placement: 'MAIN',
    orderIndex: 4,
    status: 'NOT_STARTED',
    wordLimit: 1000,
    wordCount: 33,
    includeInExport: true,
    content:
      'The reproducibility of the gapless surface state across growth runs is the key result for qubit applications [@moore2010]. Future work will pattern these films into device geometries and probe coherence.',
    notes: '',
  }),
  makeRecord('manuscriptSection', 'ti-data-availability', 5, {
    name: 'Data availability',
    manuscriptId: MANUSCRIPT,
    sectionType: 'DATA_AVAILABILITY',
    placement: 'BACK_MATTER',
    orderIndex: 5,
    status: 'DRAFTING',
    wordLimit: 0,
    wordCount: 18,
    includeInExport: true,
    content:
      'The ARPES and transport datasets are available in the lab repository and are catalogued under the project’s datasets.',
    notes: '',
  }),
  makeRecord('manuscriptSection', 'ti-supplementary-methods', 6, {
    name: 'Supplementary methods',
    manuscriptId: MANUSCRIPT,
    sectionType: 'SUPPLEMENT',
    placement: 'SUPPLEMENT',
    orderIndex: 0,
    status: 'DRAFTING',
    wordLimit: 0,
    wordCount: 24,
    includeInExport: true,
    content:
      'Extended X-ray diffraction characterization of film crystallinity is shown in [#fig:sup-xrd]. Substrate temperature and flux ratios were logged for every run.',
    notes: '',
  }),
];

const figureRecords = (): SeedRecord[] => [
  makeRecord('figure', 'fig-bandstructure', 0, {
    name: 'Dirac-cone schematic',
    manuscriptId: MANUSCRIPT,
    sectionId: SECTION('ti-intro'),
    assetKind: 'FIGURE',
    placement: 'MAIN',
    refKey: 'bandstructure',
    caption:
      'Schematic of the topological surface-state Dirac cone within the bulk band gap.',
    imageSource: 'NONE',
    imageUrl: '',
    altText: 'Dirac cone band structure schematic',
    credit: '',
    widthPercent: 60,
    orderIndex: 0,
    notes: '',
  }),
  makeRecord('figure', 'tab-growth', 1, {
    name: 'Growth parameters',
    manuscriptId: MANUSCRIPT,
    sectionId: SECTION('ti-methods'),
    assetKind: 'TABLE',
    placement: 'MAIN',
    refKey: 'growth',
    caption:
      'MBE growth parameters: substrate temperature, flux ratio, and growth rate per run.',
    imageSource: 'NONE',
    imageUrl: '',
    tableData:
      '| Run | Substrate T (°C) | Se:Bi flux ratio | Rate (nm/min) |\n| --- | --- | --- | --- |\n| A | 220 | 10:1 | 0.8 |\n| B | 240 | 8:1 | 1.1 |\n| C | 200 | 12:1 | 0.6 |',
    altText: '',
    credit: '',
    widthPercent: 100,
    orderIndex: 1,
    notes: '',
  }),
  makeRecord('figure', 'fig-arpes', 2, {
    name: 'ARPES spectrum',
    manuscriptId: MANUSCRIPT,
    sectionId: SECTION('ti-results'),
    datasetId: recordId('dataset', 'arpes-spectra'),
    assetKind: 'FIGURE',
    placement: 'MAIN',
    refKey: 'arpes',
    caption:
      'ARPES intensity map showing a single sharp Dirac cone at the Γ point.',
    imageSource: 'DATASET',
    imageUrl: '',
    altText: 'ARPES intensity map with Dirac cone',
    credit: 'Data: Quantum Materials Lab',
    widthPercent: 80,
    orderIndex: 2,
    notes: 'Plotted from the ARPES dataset.',
  }),
  makeRecord('figure', 'fig-sup-xrd', 3, {
    name: 'Supplementary XRD',
    manuscriptId: MANUSCRIPT,
    sectionId: SECTION('ti-supplementary-methods'),
    assetKind: 'FIGURE',
    placement: 'SUPPLEMENT',
    refKey: 'sup-xrd',
    caption:
      'X-ray diffraction confirming single-phase, c-axis-oriented films.',
    imageSource: 'NONE',
    imageUrl: '',
    altText: 'XRD pattern',
    credit: '',
    widthPercent: 70,
    orderIndex: 0,
    notes: '',
  }),
];

// Seed map keyed by object `nameSingular`, matching the DataSource seed shape.
export const getResearchSeedRecords = (): Record<string, SeedRecord[]> => ({
  researchTeam: researchTeamRecords(),
  researcher: researcherRecords(),
  project: projectRecords(),
  grant: grantRecords(),
  grantSource: grantSourceRecords(),
  grantOpportunity: grantOpportunityRecords(),
  grantApplication: grantApplicationRecords(),
  applicationCycle: applicationCycleRecords(),
  milestone: milestoneRecords(),
  dataset: datasetRecords(),
  manuscript: manuscriptRecords(),
  applicationRequirement: applicationRequirementRecords(),
  applicantProfile: applicantProfileRecords(),
  applicationSection: applicationSectionRecords(),
  reusableAnswer: reusableAnswerRecords(),
  journalTemplate: journalTemplateRecords(),
  reference: referenceRecords(),
  manuscriptSection: manuscriptSectionRecords(),
  figure: figureRecords(),
});
