import { researchDeterministicUuid } from './researchMetadataBuilder';
import { RESEARCH_GRANT_SOURCE_SEEDS } from './researchGrantSourceData';

// Demo seed records for the research objects. Mirrors how the bridge seeds the
// standard CRM (company/person/…) so a fresh local workspace opens with a
// coherent research team, live grant sources, and a few grants/opportunities to
// click through. Keys are object `nameSingular` to match the DataSource seed
// map. Relations are wired via `<field>Id` join columns pointing at parent
// record ids (see researchRelations.ts).

type SeedRecord = Record<string, unknown> & { id: string };

const ACTOR = {
  source: 'MANUAL',
  workspaceMemberId: null,
  name: 'Seed',
  context: null,
};

const SEED_TIMESTAMP = '2026-04-10T08:55:57.800Z';

// Stable id for a seed record, by object + key. Used both as a record's own id
// and as the join-column value on related records.
const recordId = (objectNameSingular: string, key: string): string =>
  researchDeterministicUuid(`research:record:${objectNameSingular}:${key}`);

const makeRecord = (
  objectNameSingular: string,
  key: string,
  position: number,
  fields: Record<string, unknown>,
): SeedRecord => ({
  id: recordId(objectNameSingular, key),
  createdAt: SEED_TIMESTAMP,
  updatedAt: SEED_TIMESTAMP,
  deletedAt: null,
  position,
  createdBy: ACTOR,
  updatedBy: ACTOR,
  ...fields,
});

const TEAM = recordId('researchTeam', 'quantum-materials-lab');
const RESEARCHER = {
  maya: recordId('researcher', 'maya-okafor'),
  liam: recordId('researcher', 'liam-tran'),
  sofia: recordId('researcher', 'sofia-reyes'),
  noah: recordId('researcher', 'noah-bell'),
};
const PROJECT = {
  topological: recordId('project', 'topological-insulators'),
  spintronic: recordId('project', 'spintronic-memory'),
  cryo: recordId('project', 'cryo-instrumentation'),
};
const GRANT = {
  nserc: recordId('grant', 'nserc-discovery'),
  innovate: recordId('grant', 'innovate-bc-ignite'),
};
const CYCLE = {
  fall: recordId('applicationCycle', 'fall-2026-tri-agency'),
  spring: recordId('applicationCycle', 'spring-2026-industry'),
};
const APP = {
  cihrTeam: recordId('grantApplication', 'cihr-team-app'),
  innovate: recordId('grantApplication', 'innovate-ignite-app'),
  mitacs: recordId('grantApplication', 'mitacs-app'),
  nsercRenewal: recordId('grantApplication', 'nserc-renewal-app'),
};
const SOURCE = (libraryKey: string) => recordId('grantSource', libraryKey);

const grantSourceRecords = (): SeedRecord[] =>
  RESEARCH_GRANT_SOURCE_SEEDS.map((source, index) =>
    makeRecord('grantSource', source.libraryKey, index, {
      name: source.name,
      url: source.url,
      sourceType: source.sourceType,
      jurisdiction: source.jurisdiction,
      funderType: source.funderType,
      topicTags: source.topicTags,
      eligibilityTags: source.eligibilityTags,
      scrapeCadence: source.scrapeCadence,
      trustLevel: source.trustLevel,
      status: source.status,
      lastScrapedAt: null,
      notes: source.notes,
    }),
  );

const researchTeamRecords = (): SeedRecord[] => [
  makeRecord('researchTeam', 'quantum-materials-lab', 0, {
    name: 'Quantum Materials Lab',
    principalInvestigator: 'Dr. Maya Okafor',
    institution: 'University of British Columbia',
    department: 'Department of Physics & Astronomy',
    focusAreas: ['quantum materials', 'spintronics', 'low-temperature physics'],
    individualMode: false,
    website: 'https://qml.example.ubc.ca',
    notes: 'Core lab workspace for the quantum materials group.',
  }),
];

const researcherRecords = (): SeedRecord[] => [
  makeRecord('researcher', 'maya-okafor', 0, {
    name: 'Dr. Maya Okafor',
    email: 'maya.okafor@example.ubc.ca',
    role: 'PI',
    teamId: TEAM,
    orcid: '0000-0002-1825-0097',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Principal investigator.',
  }),
  makeRecord('researcher', 'liam-tran', 1, {
    name: 'Liam Tran',
    email: 'liam.tran@example.ubc.ca',
    role: 'POSTDOC',
    teamId: TEAM,
    orcid: '0000-0001-7300-1234',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Leads the spintronics sub-project.',
  }),
  makeRecord('researcher', 'sofia-reyes', 2, {
    name: 'Sofia Reyes',
    email: 'sofia.reyes@example.ubc.ca',
    role: 'PHD',
    teamId: TEAM,
    orcid: '0000-0003-4444-9876',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Thesis on topological insulators.',
  }),
  makeRecord('researcher', 'noah-bell', 3, {
    name: 'Noah Bell',
    email: 'noah.bell@example.ubc.ca',
    role: 'RESEARCH_ASSISTANT',
    teamId: TEAM,
    orcid: '',
    institution: 'University of British Columbia',
    status: 'ACTIVE',
    notes: 'Sample fabrication and lab operations.',
  }),
];

const projectRecords = (): SeedRecord[] => [
  makeRecord('project', 'topological-insulators', 0, {
    name: 'Topological insulators for fault-tolerant qubits',
    leadId: RESEARCHER.sofia,
    teamId: TEAM,
    status: 'ACTIVE',
    fundingStatus: 'PARTIALLY_FUNDED',
    summary:
      'Growth and characterization of topological insulator thin films for robust qubit substrates.',
    startDate: '2025-09-01T00:00:00.000Z',
    endDate: '2028-08-31T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('project', 'spintronic-memory', 1, {
    name: 'Low-power spintronic memory devices',
    leadId: RESEARCHER.liam,
    teamId: TEAM,
    status: 'ACTIVE',
    fundingStatus: 'SEEKING',
    summary: 'Prototyping energy-efficient magnetic memory cells.',
    startDate: '2026-01-15T00:00:00.000Z',
    endDate: '2027-12-31T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('project', 'cryo-instrumentation', 2, {
    name: 'Shared cryogenic measurement platform',
    leadId: RESEARCHER.maya,
    teamId: TEAM,
    status: 'PLANNING',
    fundingStatus: 'UNFUNDED',
    summary: 'Infrastructure project for a shared dilution-refrigerator setup.',
    startDate: null,
    endDate: null,
    notes: 'Candidate for an infrastructure / equipment grant.',
  }),
];

const grantRecords = (): SeedRecord[] => [
  makeRecord('grant', 'nserc-discovery', 0, {
    name: 'Quantum materials core program',
    funder: 'Natural Sciences and Engineering Research Council',
    program: 'Discovery Grants',
    status: 'ACTIVE',
    priority: 'HIGH',
    projectId: PROJECT.topological,
    leadId: RESEARCHER.maya,
    amountRequested: 600000,
    amountAwarded: 540000,
    fitScore: 5,
    applicationDueDate: '2025-11-01T00:00:00.000Z',
    submittedAt: '2025-10-28T00:00:00.000Z',
    decisionAt: '2026-04-01T00:00:00.000Z',
    startDate: '2026-04-01T00:00:00.000Z',
    endDate: '2031-03-31T00:00:00.000Z',
    nextReportDue: '2026-12-31T00:00:00.000Z',
    opportunityUrl: 'https://www.nserc-crsng.gc.ca/professors-professeurs/grants-subs/dgigp-psigp_eng.asp',
    nextAction: 'Prepare year-1 progress report',
    notes: '',
  }),
  makeRecord('grant', 'cihr-project', 1, {
    name: 'Quantum sensing for early diagnostics',
    funder: 'Canadian Institutes of Health Research',
    program: 'Project Grant',
    status: 'SUBMITTED',
    priority: 'HIGH',
    projectId: PROJECT.spintronic,
    leadId: RESEARCHER.liam,
    amountRequested: 450000,
    amountAwarded: null,
    fitScore: 3,
    applicationDueDate: '2026-03-03T00:00:00.000Z',
    submittedAt: '2026-03-01T00:00:00.000Z',
    decisionAt: null,
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl: 'https://www.researchnet-recherchenet.ca/',
    nextAction: 'Await notice of decision',
    notes: '',
  }),
  makeRecord('grant', 'innovate-bc-ignite', 2, {
    name: 'Spintronic memory commercialization',
    funder: 'Innovate BC',
    program: 'Ignite',
    status: 'DRAFTING',
    priority: 'MEDIUM',
    projectId: PROJECT.spintronic,
    leadId: RESEARCHER.liam,
    amountRequested: 300000,
    amountAwarded: null,
    fitScore: 4,
    applicationDueDate: '2026-07-15T00:00:00.000Z',
    submittedAt: null,
    decisionAt: null,
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl: 'https://www.innovatebc.ca/',
    nextAction: 'Draft commercialization plan',
    notes: 'Requires an industry partner match.',
  }),
  makeRecord('grant', 'cfi-jelf', 3, {
    name: 'Shared cryogenic measurement platform',
    funder: 'Canada Foundation for Innovation',
    program: 'John R. Evans Leaders Fund',
    status: 'PROSPECTING',
    priority: 'MEDIUM',
    projectId: PROJECT.cryo,
    leadId: RESEARCHER.maya,
    amountRequested: 250000,
    amountAwarded: null,
    fitScore: 4,
    applicationDueDate: '2026-10-01T00:00:00.000Z',
    submittedAt: null,
    decisionAt: null,
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl: 'https://www.innovation.ca/',
    nextAction: 'Confirm institutional support',
    notes: '',
  }),
  makeRecord('grant', 'nfrf-exploration', 4, {
    name: 'Topological qubits feasibility study',
    funder: 'Tri-Agency (NFRF)',
    program: 'Exploration',
    status: 'DECLINED',
    priority: 'LOW',
    projectId: PROJECT.topological,
    leadId: RESEARCHER.sofia,
    amountRequested: 250000,
    amountAwarded: null,
    fitScore: 2,
    applicationDueDate: '2025-02-15T00:00:00.000Z',
    submittedAt: '2025-02-10T00:00:00.000Z',
    decisionAt: '2025-07-01T00:00:00.000Z',
    startDate: null,
    endDate: null,
    nextReportDue: null,
    opportunityUrl: 'https://www.sshrc-crsh.gc.ca/funding-financement/nfrf-fnfr/',
    nextAction: 'Revise and resubmit next cycle',
    notes: 'Reviewers wanted clearer interdisciplinary scope.',
  }),
];

const grantOpportunityRecords = (): SeedRecord[] => [
  makeRecord('grantOpportunity', 'cihr-team-grant', 0, {
    name: 'Quantum technologies for health',
    funder: 'Canadian Institutes of Health Research',
    program: 'Team Grant',
    sourceId: SOURCE('cihr-researchnet'),
    opportunityUrl: 'https://www.researchnet-recherchenet.ca/',
    applicationDueDate: '2026-09-15T00:00:00.000Z',
    registrationDueDate: '2026-07-01T00:00:00.000Z',
    amountText: 'Up to $1,500,000 over 5 years',
    fitScore: 4,
    confidence: 'HIGH',
    status: 'NEW',
    eligibility: 'Canadian institutions; interdisciplinary teams',
    topicTags: ['health', 'quantum', 'team'],
    description:
      'Funds interdisciplinary teams applying quantum technologies to health challenges.',
  }),
  makeRecord('grantOpportunity', 'innovate-bc-ignite-2026', 1, {
    name: 'Fall 2026 commercialization intake',
    funder: 'Innovate BC',
    program: 'Ignite',
    sourceId: SOURCE('innovate-bc'),
    opportunityUrl: 'https://www.innovatebc.ca/',
    applicationDueDate: '2026-07-15T00:00:00.000Z',
    registrationDueDate: null,
    amountText: 'Up to $300,000',
    fitScore: 5,
    confidence: 'HIGH',
    status: 'REVIEWING',
    eligibility: 'BC-based research with industry partner',
    topicTags: ['bc', 'commercialization', 'tech'],
    description: 'Funds late-stage research with a clear path to commercialization.',
  }),
  makeRecord('grantOpportunity', 'ndit-grant-writing', 2, {
    name: 'Grant writing support reimbursement',
    funder: 'Northern Development Initiative Trust',
    program: 'Grant Writing Support',
    sourceId: SOURCE('northern-development-initiative-trust'),
    opportunityUrl: 'https://www.northerndevelopment.bc.ca/',
    applicationDueDate: null,
    registrationDueDate: null,
    amountText: 'Up to $2,500 (matching)',
    fitScore: 2,
    confidence: 'MEDIUM',
    status: 'NEW',
    eligibility: 'Northern BC organizations',
    topicTags: ['bc', 'capacity', 'matching'],
    description: 'Reimburses a portion of professional grant-writing costs.',
  }),
  makeRecord('grantOpportunity', 'nrc-collaboration', 3, {
    name: 'Collaborative R&D with NRC labs',
    funder: 'National Research Council Canada',
    program: 'Collaborative R&D',
    sourceId: SOURCE('nrc-research-collaboration'),
    opportunityUrl: 'https://nrc.canada.ca/',
    applicationDueDate: '2026-08-30T00:00:00.000Z',
    registrationDueDate: null,
    amountText: 'Negotiated',
    fitScore: 4,
    confidence: 'MEDIUM',
    status: 'NEW',
    eligibility: 'Canadian researchers partnering with NRC',
    topicTags: ['materials', 'collaboration'],
    description: 'Co-funded collaborative research with NRC laboratories.',
  }),
  makeRecord('grantOpportunity', 'mitacs-accelerate', 4, {
    name: 'Graduate internship with industry partner',
    funder: 'Mitacs',
    program: 'Accelerate',
    sourceId: SOURCE('innovate-bc'),
    opportunityUrl: 'https://www.mitacs.ca/',
    applicationDueDate: null,
    registrationDueDate: null,
    amountText: '$15,000 per 4-month unit',
    fitScore: 3,
    confidence: 'HIGH',
    status: 'ACCEPTED',
    eligibility: 'Graduate students with industry partner',
    topicTags: ['internship', 'students', 'partner'],
    description: 'Funds graduate internships co-supervised with industry.',
  }),
  makeRecord('grantOpportunity', 'first-nations-clean-energy', 5, {
    name: 'First Nations clean energy stream',
    funder: 'Province of British Columbia',
    program: 'Clean Energy Business Fund',
    sourceId: SOURCE('first-nations-clean-energy-business-fund'),
    opportunityUrl: 'https://www2.gov.bc.ca/',
    applicationDueDate: '2026-06-30T00:00:00.000Z',
    registrationDueDate: null,
    amountText: 'Varies',
    fitScore: 1,
    confidence: 'LOW',
    status: 'REJECTED',
    eligibility: 'First Nations communities and partnerships',
    topicTags: ['energy', 'bc'],
    description: 'Out of scope for this lab — kept for completeness.',
  }),
];

const applicationCycleRecords = (): SeedRecord[] => [
  makeRecord('applicationCycle', 'fall-2026-tri-agency', 0, {
    name: 'Fall 2026 Tri-Agency push',
    status: 'OPEN',
    openDate: '2026-06-01T00:00:00.000Z',
    closeDate: '2026-09-15T00:00:00.000Z',
    focus: 'Quantum materials and sensing — flagship proposals',
    owner: 'Dr. Maya Okafor',
    description:
      'Coordinated submission window for NSERC/CIHR/NFRF aligned with the lab’s strategic needs.',
  }),
  makeRecord('applicationCycle', 'spring-2026-industry', 1, {
    name: 'Spring 2026 industry partnerships',
    status: 'REVIEWING',
    openDate: '2026-01-10T00:00:00.000Z',
    closeDate: '2026-04-30T00:00:00.000Z',
    focus: 'Commercialization and matched-funding opportunities',
    owner: 'Liam Tran',
    description: 'Innovate BC / Mitacs partnership-driven applications.',
  }),
];

const grantApplicationRecords = (): SeedRecord[] => [
  makeRecord('grantApplication', 'cihr-team-app', 0, {
    name: 'Quantum sensing platform for early diagnostics',
    applicantId: RESEARCHER.maya,
    organization: 'Quantum Materials Lab',
    email: 'maya.okafor@example.ubc.ca',
    grantId: null,
    cycleId: CYCLE.fall,
    amountRequested: 1500000,
    projectSummary: 'Interdisciplinary team proposal for quantum-enabled diagnostics.',
    status: 'REVIEWING',
    source: 'ADMIN',
    submittedAt: '2026-06-20T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('grantApplication', 'innovate-ignite-app', 1, {
    name: 'Spintronic memory commercialization',
    applicantId: RESEARCHER.liam,
    organization: 'Quantum Materials Lab',
    email: 'liam.tran@example.ubc.ca',
    grantId: GRANT.innovate,
    cycleId: CYCLE.spring,
    amountRequested: 300000,
    projectSummary: 'Late-stage development with a hardware partner.',
    status: 'SHORTLISTED',
    source: 'PORTAL',
    submittedAt: '2026-04-15T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('grantApplication', 'mitacs-app', 2, {
    name: 'Graduate internship — topological thin films',
    applicantId: RESEARCHER.sofia,
    organization: 'Quantum Materials Lab',
    email: 'sofia.reyes@example.ubc.ca',
    grantId: null,
    cycleId: CYCLE.spring,
    amountRequested: 60000,
    projectSummary: 'Four internship units co-supervised with an industry partner.',
    status: 'APPROVED',
    source: 'PORTAL',
    submittedAt: '2026-02-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('grantApplication', 'nserc-renewal-app', 3, {
    name: 'Discovery program renewal',
    applicantId: RESEARCHER.maya,
    organization: 'Quantum Materials Lab',
    email: 'maya.okafor@example.ubc.ca',
    grantId: GRANT.nserc,
    cycleId: CYCLE.fall,
    amountRequested: 600000,
    projectSummary: 'Renewal of the lab’s flagship Discovery program.',
    status: 'SUBMITTED',
    source: 'ADMIN',
    submittedAt: '2026-06-18T00:00:00.000Z',
    notes: '',
  }),
];

const milestoneRecords = (): SeedRecord[] => [
  makeRecord('milestone', 'ti-film-growth', 0, {
    name: 'Achieve reproducible TI thin-film growth',
    projectId: PROJECT.topological,
    ownerId: RESEARCHER.sofia,
    status: 'IN_PROGRESS',
    dueDate: '2026-09-30T00:00:00.000Z',
    progress: 60,
    notes: '',
  }),
  makeRecord('milestone', 'spintronic-prototype', 1, {
    name: 'First spintronic memory prototype',
    projectId: PROJECT.spintronic,
    ownerId: RESEARCHER.liam,
    status: 'NOT_STARTED',
    dueDate: '2026-12-15T00:00:00.000Z',
    progress: 0,
    notes: '',
  }),
  makeRecord('milestone', 'cryo-procurement', 2, {
    name: 'Dilution refrigerator procurement',
    projectId: PROJECT.cryo,
    ownerId: RESEARCHER.maya,
    status: 'BLOCKED',
    dueDate: '2026-11-01T00:00:00.000Z',
    progress: 10,
    notes: 'Blocked on infrastructure funding.',
  }),
  makeRecord('milestone', 'year1-report', 3, {
    name: 'NSERC year-1 progress report',
    projectId: PROJECT.topological,
    ownerId: RESEARCHER.maya,
    status: 'IN_PROGRESS',
    dueDate: '2026-12-31T00:00:00.000Z',
    progress: 25,
    notes: '',
  }),
  makeRecord('milestone', 'sample-pipeline', 4, {
    name: 'Standardize sample fabrication pipeline',
    projectId: PROJECT.spintronic,
    ownerId: RESEARCHER.noah,
    status: 'DONE',
    dueDate: '2026-03-31T00:00:00.000Z',
    progress: 100,
    notes: '',
  }),
];

const datasetRecords = (): SeedRecord[] => [
  makeRecord('dataset', 'arpes-spectra', 0, {
    name: 'ARPES spectra — TI thin films',
    projectId: PROJECT.topological,
    dataType: 'IMAGING',
    status: 'ANALYSIS',
    storageLocation: 'Lab NAS / arpes/2026',
    sizeGb: 420,
    hasEthicsApproval: false,
    collectedAt: '2026-05-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('dataset', 'transport-measurements', 1, {
    name: 'Magnetotransport measurements',
    projectId: PROJECT.spintronic,
    dataType: 'TABULAR',
    status: 'COLLECTING',
    storageLocation: 'Lab NAS / transport/2026',
    sizeGb: 35,
    hasEthicsApproval: false,
    collectedAt: '2026-06-01T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('dataset', 'fabrication-logs', 2, {
    name: 'Sample fabrication logbook',
    projectId: PROJECT.spintronic,
    dataType: 'TEXT',
    status: 'COLLECTING',
    storageLocation: 'Electronic lab notebook',
    sizeGb: 1,
    hasEthicsApproval: false,
    collectedAt: '2026-01-15T00:00:00.000Z',
    notes: '',
  }),
  makeRecord('dataset', 'dft-simulations', 3, {
    name: 'DFT simulation outputs',
    projectId: PROJECT.topological,
    dataType: 'OTHER',
    status: 'ARCHIVED',
    storageLocation: 'Compute cluster / scratch archived to NAS',
    sizeGb: 180,
    hasEthicsApproval: false,
    collectedAt: '2025-12-01T00:00:00.000Z',
    notes: '',
  }),
];

const manuscriptRecords = (): SeedRecord[] => [
  makeRecord('manuscript', 'ti-qubit-substrates', 0, {
    name: 'Topological insulator substrates for robust qubits',
    projectId: PROJECT.topological,
    leadAuthorId: RESEARCHER.sofia,
    manuscriptType: 'JOURNAL_PAPER',
    status: 'DRAFTING',
    targetVenue: 'Nature Materials',
    progress: 40,
    targetDate: '2026-11-30T00:00:00.000Z',
    doi: '',
    notes: '',
  }),
  makeRecord('manuscript', 'reyes-thesis', 1, {
    name: 'PhD thesis — Topological materials for quantum computing',
    projectId: PROJECT.topological,
    leadAuthorId: RESEARCHER.sofia,
    manuscriptType: 'THESIS',
    status: 'OUTLINE',
    targetVenue: 'UBC',
    progress: 15,
    targetDate: '2028-06-30T00:00:00.000Z',
    doi: '',
    notes: '',
  }),
  makeRecord('manuscript', 'spintronic-preprint', 2, {
    name: 'Energy-efficient spintronic memory: a preprint',
    projectId: PROJECT.spintronic,
    leadAuthorId: RESEARCHER.liam,
    manuscriptType: 'PREPRINT',
    status: 'SUBMITTED',
    targetVenue: 'arXiv',
    progress: 90,
    targetDate: '2026-07-31T00:00:00.000Z',
    doi: '10.48550/arXiv.2606.00000',
    notes: '',
  }),
  makeRecord('manuscript', 'cryo-methods', 3, {
    name: 'A shared cryogenic measurement platform (methods)',
    projectId: PROJECT.cryo,
    leadAuthorId: RESEARCHER.maya,
    manuscriptType: 'CONFERENCE_PAPER',
    status: 'INTERNAL_REVIEW',
    targetVenue: 'APS March Meeting',
    progress: 70,
    targetDate: '2026-10-01T00:00:00.000Z',
    doi: '',
    notes: '',
  }),
];

const applicationRequirementRecords = (): SeedRecord[] => [
  // CIHR Team Grant application checklist
  makeRecord('applicationRequirement', 'cihr-narrative', 0, {
    name: 'Research narrative (10 pages)',
    applicationId: APP.cihrTeam,
    category: 'NARRATIVE',
    status: 'READY',
    dueDate: '2026-09-01T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'cihr-budget', 1, {
    name: 'Budget and justification',
    applicationId: APP.cihrTeam,
    category: 'BUDGET',
    status: 'NEEDED',
    dueDate: '2026-09-05T00:00:00.000Z',
    formNumber: '',
    notes: 'Coordinate with finance office.',
  }),
  makeRecord('applicationRequirement', 'cihr-ccv', 2, {
    name: 'Common CV for all team members',
    applicationId: APP.cihrTeam,
    category: 'CV',
    status: 'REQUESTED',
    dueDate: '2026-09-01T00:00:00.000Z',
    formNumber: 'CCV',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'cihr-ethics', 3, {
    name: 'Ethics approval (REB)',
    applicationId: APP.cihrTeam,
    category: 'ETHICS',
    status: 'NEEDED',
    dueDate: '2026-09-10T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  // Innovate BC Ignite checklist
  makeRecord('applicationRequirement', 'ignite-commercialization', 4, {
    name: 'Commercialization plan',
    applicationId: APP.innovate,
    category: 'NARRATIVE',
    status: 'READY',
    dueDate: '2026-07-10T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'ignite-partner-letter', 5, {
    name: 'Industry partner letter of support',
    applicationId: APP.innovate,
    category: 'LETTER_OF_SUPPORT',
    status: 'ATTACHED',
    dueDate: '2026-07-01T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'ignite-budget', 6, {
    name: 'Matched-funding budget',
    applicationId: APP.innovate,
    category: 'BUDGET',
    status: 'READY',
    dueDate: '2026-07-10T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  // Mitacs internship checklist
  makeRecord('applicationRequirement', 'mitacs-proposal', 7, {
    name: 'Internship research proposal',
    applicationId: APP.mitacs,
    category: 'NARRATIVE',
    status: 'ATTACHED',
    dueDate: '2026-01-25T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'mitacs-partner-form', 8, {
    name: 'Partner organization form',
    applicationId: APP.mitacs,
    category: 'FORM',
    status: 'ATTACHED',
    dueDate: '2026-01-25T00:00:00.000Z',
    formNumber: 'MITACS-PO',
    notes: '',
  }),
  // NSERC Discovery renewal checklist
  makeRecord('applicationRequirement', 'nserc-proposal', 9, {
    name: 'Discovery proposal (5 pages)',
    applicationId: APP.nsercRenewal,
    category: 'NARRATIVE',
    status: 'READY',
    dueDate: '2026-06-15T00:00:00.000Z',
    formNumber: 'Form 101',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'nserc-ccv', 10, {
    name: 'NSERC CCV',
    applicationId: APP.nsercRenewal,
    category: 'CV',
    status: 'ATTACHED',
    dueDate: '2026-06-10T00:00:00.000Z',
    formNumber: 'CCV',
    notes: '',
  }),
  makeRecord('applicationRequirement', 'nserc-hqp', 11, {
    name: 'HQP training plan',
    applicationId: APP.nsercRenewal,
    category: 'OTHER',
    status: 'REQUESTED',
    dueDate: '2026-06-15T00:00:00.000Z',
    formNumber: '',
    notes: '',
  }),
];

// Seed map keyed by object `nameSingular`, matching the DataSource seed shape.
export const getResearchSeedRecords = (): Record<string, SeedRecord[]> => ({
  researchTeam: researchTeamRecords(),
  researcher: researcherRecords(),
  project: projectRecords(),
  grant: grantRecords(),
  grantSource: grantSourceRecords(),
  grantOpportunity: grantOpportunityRecords(),
  grantApplication: grantApplicationRecords(),
  applicationCycle: applicationCycleRecords(),
  milestone: milestoneRecords(),
  dataset: datasetRecords(),
  manuscript: manuscriptRecords(),
  applicationRequirement: applicationRequirementRecords(),
});
