// Generic DataSource dispatcher backed by Convex. Pairs with the schema
// auto-generated by `generateConvexSchema(bundle)` — every table is a Twenty
// object addressable by its `nameSingular`.
//
// Convex's HTTP actions can't touch the db directly; reads + writes have to
// flow through `internalQuery` / `internalMutation` and be invoked via
// `ctx.runQuery` / `ctx.runMutation`. This file exposes:
//   * `*Impl` — internalQuery / internalMutation that hold the db logic.
//   * `*Action` — httpAction wrappers that parse a JSON body and delegate.
//
// Filter / sort semantics match the Dexie + in-memory adapters by reusing
// `twenty-shared/data-source` utilities. Native Convex filter translation is
// best-effort: anything `tryBuildConvexFilter` can't express degrades to a
// full `collect()` + JS predicate.

import { v } from 'convex/values';

import { httpAction, internalMutation, internalQuery } from './_generated/server';
import { internal } from './_generated/api';
import {
  checkBridgeAuth,
  errorResponse,
  okResponse,
} from './bridgeAuth';
import {
  buildActorFromContext,
  computeAggregate,
  computeDuplicates,
  computeSearch,
  decodeCursor,
  encodeCursor,
  filterToPredicate,
  orderByToComparator,
  scopeFilterByContext,
  tryBuildConvexFilter,
  type DataSourceContext,
  type DataSourceFindManyArgs,
  type DataSourceFindOneArgs,
  type DataSourceRecord,
  type DataSourceSearchArgs,
} from 'twenty-shared/data-source';
import { type RecordGqlOperationFilter } from 'twenty-shared/types';

type ConvexReader = {
  query: (name: string) => {
    filter: (
      cb: (q: unknown) => unknown,
    ) => { collect: () => Promise<DataSourceRecord[]> };
    collect: () => Promise<DataSourceRecord[]>;
  };
};

type ConvexWriter = ConvexReader & {
  insert: (name: string, value: unknown) => Promise<string>;
  replace: (id: string, value: unknown) => Promise<void>;
  delete: (id: string) => Promise<void>;
};

// Convex's schema validator distinguishes `null` from `undefined`; the
// auto-generated schema marks `deletedAt` as `v.optional(v.string())`, which
// accepts an absent field but rejects an explicit `null`. Records are created
// without `deletedAt`; soft-delete sets it to an ISO string.
const STRIP_NULL_DELETED_AT = (record: Record<string, unknown>) => {
  if (record.deletedAt === null || record.deletedAt === undefined) {
    const { deletedAt: _, ...rest } = record;
    return rest;
  }
  return record;
};

const includesDeletedClause = (
  filter: RecordGqlOperationFilter | null | undefined,
): boolean => {
  if (!filter || typeof filter !== 'object') return false;
  const candidate = filter as Record<string, unknown>;
  if (typeof candidate.deletedAt === 'object' && candidate.deletedAt !== null)
    return true;
  if (Array.isArray(candidate.or))
    return candidate.or.some((subFilter) =>
      includesDeletedClause(subFilter as RecordGqlOperationFilter),
    );
  return false;
};

const fetchRecords = async (
  db: ConvexReader,
  objectName: string,
  filter: RecordGqlOperationFilter | null | undefined,
  context: DataSourceContext,
): Promise<DataSourceRecord[]> => {
  const scopedFilter = scopeFilterByContext(filter, context);
  const showDeleted = includesDeletedClause(scopedFilter ?? undefined);

  const composedFilter: RecordGqlOperationFilter | null = showDeleted
    ? (scopedFilter ?? null)
    : ({
        and: [
          ...(scopedFilter ? [scopedFilter] : []),
          { deletedAt: { is: 'NULL' } },
        ],
      } as RecordGqlOperationFilter);

  const nativeBuilder = tryBuildConvexFilter(composedFilter);
  if (nativeBuilder !== null) {
    return db
      .query(objectName)
      .filter((q) => nativeBuilder(q as never))
      .collect();
  }
  const all = await db.query(objectName).collect();
  const visible = showDeleted
    ? all
    : all.filter(
        (record) => record.deletedAt === null || record.deletedAt === undefined,
      );
  const predicate = filterToPredicate(scopedFilter ?? undefined);
  return visible.filter(predicate);
};

const lookupOne = async (
  db: ConvexReader,
  objectName: string,
  id: string,
): Promise<DataSourceRecord | undefined> => {
  const native = tryBuildConvexFilter({
    id: { eq: id },
  } as RecordGqlOperationFilter);
  if (native !== null) {
    const matches = await db
      .query(objectName)
      .filter((q) => native(q as never))
      .collect();
    return matches[0];
  }
  const all = await db.query(objectName).collect();
  return all.find((record) => record.id === id);
};

const findManyResult = async (
  db: ConvexReader,
  args: {
    objectName: string;
    args: DataSourceFindManyArgs;
    context: DataSourceContext;
  },
) => {
  const matched = await fetchRecords(
    db,
    args.objectName,
    args.args.filter,
    args.context,
  );
  const sorted = [...matched].sort(orderByToComparator(args.args.orderBy ?? null));

  const offset = args.args.offset ?? 0;
  const startCursor = decodeCursor(args.args.after ?? undefined);
  const baseIndex = (startCursor !== null ? startCursor + 1 : 0) + offset;
  const limit =
    typeof args.args.first === 'number'
      ? args.args.first
      : typeof args.args.last === 'number'
        ? args.args.last
        : sorted.length - baseIndex;

  const slice = sorted.slice(baseIndex, baseIndex + limit);
  const startIndex = baseIndex;
  const endIndex = baseIndex + slice.length - 1;

  return {
    records: slice,
    pageInfo: {
      hasNextPage: baseIndex + slice.length < sorted.length,
      hasPreviousPage: startIndex > 0,
      startCursor: slice.length > 0 ? encodeCursor(startIndex) : null,
      endCursor: slice.length > 0 ? encodeCursor(endIndex) : null,
    },
    totalCount: matched.length,
  };
};

const sameWorkspace = (
  existing: DataSourceRecord,
  context: DataSourceContext,
): boolean =>
  !context.workspaceId ||
  typeof existing.workspaceId !== 'string' ||
  existing.workspaceId === context.workspaceId;

// Internal queries: the db-touching read paths. Convex requires a validator
// for `args`; we use `v.any()` because the dispatch is generic across all 33
// tables and JSON shapes are validated upstream by Twenty's frontend.
export const findManyImpl = internalQuery({
  args: {
    objectName: v.string(),
    args: v.optional(v.any()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) =>
    findManyResult(ctx.db as unknown as ConvexReader, {
      objectName: payload.objectName,
      args: (payload.args ?? {}) as DataSourceFindManyArgs,
      context: (payload.context ?? {}) as DataSourceContext,
    }),
});

export const findOneImpl = internalQuery({
  args: {
    objectName: v.string(),
    args: v.optional(v.any()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const matched = await fetchRecords(
      ctx.db as unknown as ConvexReader,
      payload.objectName,
      (payload.args as DataSourceFindOneArgs)?.filter,
      (payload.context ?? {}) as DataSourceContext,
    );
    return matched[0] ?? null;
  },
});

export const findDuplicatesImpl = internalQuery({
  args: {
    objectName: v.string(),
    ids: v.array(v.string()),
    duplicateCriteria: v.optional(v.any()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    if (!payload.duplicateCriteria || payload.ids.length === 0) {
      return {
        records: [],
        pageInfo: {
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: null,
          endCursor: null,
        },
        totalCount: 0,
      };
    }
    const all = await fetchRecords(
      ctx.db as unknown as ConvexReader,
      payload.objectName,
      null,
      (payload.context ?? {}) as DataSourceContext,
    );
    const sourceRecords = all.filter((record) =>
      (payload.ids as string[]).includes(record.id),
    );
    const duplicates = computeDuplicates(
      sourceRecords,
      all,
      payload.duplicateCriteria as string[][],
    );
    return {
      records: duplicates,
      pageInfo: {
        hasNextPage: false,
        hasPreviousPage: false,
        startCursor: duplicates.length > 0 ? encodeCursor(0) : null,
        endCursor:
          duplicates.length > 0 ? encodeCursor(duplicates.length - 1) : null,
      },
      totalCount: duplicates.length,
    };
  },
});

export const aggregateImpl = internalQuery({
  args: {
    objectName: v.string(),
    args: v.optional(v.any()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const matched = await fetchRecords(
      ctx.db as unknown as ConvexReader,
      payload.objectName,
      (payload.args as { filter?: RecordGqlOperationFilter | null })?.filter,
      (payload.context ?? {}) as DataSourceContext,
    );
    return computeAggregate(
      matched,
      ((payload.args as { fields?: string[] })?.fields ?? []) as string[],
    );
  },
});

export const searchImpl = internalQuery({
  args: {
    args: v.any(),
    objectNames: v.array(v.string()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const scopedContext = (payload.context ?? {}) as DataSourceContext;
    const sources = await Promise.all(
      (payload.objectNames as string[]).map(async (objectName) => ({
        objectName,
        objectLabelSingular: objectName,
        records: (
          await fetchRecords(
            ctx.db as unknown as ConvexReader,
            objectName,
            null,
            scopedContext,
          )
        ).filter(
          (record) =>
            record.deletedAt === null || record.deletedAt === undefined,
        ),
      })),
    );
    return computeSearch(payload.args as DataSourceSearchArgs, sources);
  },
});

export const createOneImpl = internalMutation({
  args: {
    objectName: v.string(),
    input: v.optional(v.any()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const scopedContext = (payload.context ?? {}) as DataSourceContext;
    const input = (payload.input ?? {}) as Record<string, unknown>;
    const now = new Date().toISOString();
    const actor = buildActorFromContext(scopedContext);
    const record = STRIP_NULL_DELETED_AT({
      id:
        typeof input.id === 'string' && input.id.length > 0
          ? input.id
          : crypto.randomUUID(),
      ...input,
      ...(scopedContext.workspaceId
        ? { workspaceId: scopedContext.workspaceId }
        : {}),
      ...(actor && input.createdBy === undefined
        ? { createdBy: actor, updatedBy: actor }
        : {}),
      createdAt: typeof input.createdAt === 'string' ? input.createdAt : now,
      updatedAt: now,
    }) as DataSourceRecord;
    await (ctx.db as unknown as ConvexWriter).insert(payload.objectName, record);
    return { ...record, deletedAt: null };
  },
});

export const updateOneImpl = internalMutation({
  args: {
    objectName: v.string(),
    id: v.string(),
    input: v.optional(v.any()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const scopedContext = (payload.context ?? {}) as DataSourceContext;
    const existing = await lookupOne(
      ctx.db as unknown as ConvexReader,
      payload.objectName,
      payload.id,
    );
    if (!existing) return null;
    if (
      scopedContext.workspaceId &&
      typeof existing.workspaceId === 'string' &&
      existing.workspaceId !== scopedContext.workspaceId
    ) {
      return { __forbidden: true };
    }
    const actor = buildActorFromContext(scopedContext);
    const input = (payload.input ?? {}) as Record<string, unknown>;
    const next: DataSourceRecord = {
      ...existing,
      ...input,
      ...(actor && input.updatedBy === undefined ? { updatedBy: actor } : {}),
      id: existing.id,
      updatedAt: new Date().toISOString(),
    };
    await (ctx.db as unknown as ConvexWriter).replace(
      (existing as DataSourceRecord & { _id: string })._id,
      next,
    );
    return next;
  },
});

export const deleteOneImpl = internalMutation({
  args: {
    objectName: v.string(),
    id: v.string(),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const scopedContext = (payload.context ?? {}) as DataSourceContext;
    const existing = await lookupOne(
      ctx.db as unknown as ConvexReader,
      payload.objectName,
      payload.id,
    );
    if (!existing) return null;
    if (!sameWorkspace(existing, scopedContext)) return { __forbidden: true };
    const now = new Date().toISOString();
    const next: DataSourceRecord = {
      ...existing,
      deletedAt: now,
      updatedAt: now,
    };
    await (ctx.db as unknown as ConvexWriter).replace(
      (existing as DataSourceRecord & { _id: string })._id,
      next,
    );
    return next;
  },
});

export const destroyOneImpl = internalMutation({
  args: {
    objectName: v.string(),
    id: v.string(),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const scopedContext = (payload.context ?? {}) as DataSourceContext;
    const existing = await lookupOne(
      ctx.db as unknown as ConvexReader,
      payload.objectName,
      payload.id,
    );
    if (!existing) return { id: payload.id };
    if (!sameWorkspace(existing, scopedContext)) return { __forbidden: true };
    await (ctx.db as unknown as ConvexWriter).delete(
      (existing as DataSourceRecord & { _id: string })._id,
    );
    return { id: payload.id };
  },
});

export const restoreManyImpl = internalMutation({
  args: {
    objectName: v.string(),
    args: v.optional(v.any()),
    context: v.optional(v.any()),
  },
  handler: async (ctx, payload) => {
    const matched = await fetchRecords(
      ctx.db as unknown as ConvexReader,
      payload.objectName,
      (payload.args as DataSourceFindOneArgs)?.filter,
      (payload.context ?? {}) as DataSourceContext,
    );
    const restored: Array<{ id: string }> = [];
    const now = new Date().toISOString();
    for (const record of matched) {
      if (record.deletedAt) {
        const restoredRecord = STRIP_NULL_DELETED_AT({
          ...record,
          deletedAt: null,
          updatedAt: now,
        });
        await (ctx.db as unknown as ConvexWriter).replace(
          (record as DataSourceRecord & { _id: string })._id,
          restoredRecord,
        );
        restored.push({ id: record.id });
      }
    }
    return restored;
  },
});

const forbiddenResponse = (request: Request, objectName: string, id: string) =>
  errorResponse(request, 403, `Forbidden: ${objectName}/${id}`);

const notFoundResponse = (request: Request, objectName: string, id: string) =>
  errorResponse(request, 404, `Not found: ${objectName}/${id}`);

// HTTP actions: parse the JSON body, delegate to the matching internal
// function. Each frontend `createConvexDataSource` POST maps 1:1 here.
// Every action gates on `checkBridgeAuth` (shared-secret header + origin
// allowlist) before reading the body.
export const findManyAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = await request.json();
  return okResponse(
    request,
    await ctx.runQuery(internal.dataSource.findManyImpl, body),
  );
});

export const findOneAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = await request.json();
  return okResponse(
    request,
    await ctx.runQuery(internal.dataSource.findOneImpl, body),
  );
});

export const findDuplicatesAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = await request.json();
  return okResponse(
    request,
    await ctx.runQuery(internal.dataSource.findDuplicatesImpl, body),
  );
});

export const aggregateAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = await request.json();
  return okResponse(
    request,
    await ctx.runQuery(internal.dataSource.aggregateImpl, body),
  );
});

export const searchAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = await request.json();
  return okResponse(
    request,
    await ctx.runQuery(internal.dataSource.searchImpl, body),
  );
});

export const createOneAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = await request.json();
  return okResponse(
    request,
    await ctx.runMutation(internal.dataSource.createOneImpl, body),
  );
});

export const updateOneAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = (await request.json()) as {
    objectName: string;
    id: string;
    input?: unknown;
    context?: unknown;
  };
  const result = await ctx.runMutation(internal.dataSource.updateOneImpl, body);
  if (result === null) return notFoundResponse(request, body.objectName, body.id);
  if ((result as { __forbidden?: boolean }).__forbidden)
    return forbiddenResponse(request, body.objectName, body.id);
  return okResponse(request, result);
});

export const deleteOneAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = (await request.json()) as {
    objectName: string;
    id: string;
    input?: unknown;
    context?: unknown;
  };
  const result = await ctx.runMutation(internal.dataSource.deleteOneImpl, body);
  if (result === null) return notFoundResponse(request, body.objectName, body.id);
  if ((result as { __forbidden?: boolean }).__forbidden)
    return forbiddenResponse(request, body.objectName, body.id);
  return okResponse(request, result);
});

export const destroyOneAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = (await request.json()) as {
    objectName: string;
    id: string;
    input?: unknown;
    context?: unknown;
  };
  const result = await ctx.runMutation(
    internal.dataSource.destroyOneImpl,
    body,
  );
  if ((result as { __forbidden?: boolean }).__forbidden)
    return forbiddenResponse(request, body.objectName, body.id);
  return okResponse(request, result);
});

export const restoreManyAction = httpAction(async (ctx, request) => {
  const authError = checkBridgeAuth(request);
  if (authError) return authError;
  const body = await request.json();
  return okResponse(
    request,
    await ctx.runMutation(internal.dataSource.restoreManyImpl, body),
  );
});
