// Generic DataSource dispatcher backed by Convex. Pairs with the schema
// auto-generated by `generateConvexSchema(bundle)` — every table is a Twenty
// object addressable by its `nameSingular`.
//
// Filter / sort semantics match the Dexie + in-memory adapters by reusing
// the shared utilities from `twenty-shared/data-source`. Convex's typed db
// API expects literal table names; we widen via `as never` so a single
// implementation covers all 33 tables.

import { httpAction } from './_generated/server';
import {
  computeAggregate,
  computeSearch,
  decodeCursor,
  encodeCursor,
  filterToPredicate,
  orderByToComparator,
  type DataSourceFindManyArgs,
  type DataSourceFindOneArgs,
  type DataSourceRecord,
  type DataSourceSearchArgs,
} from 'twenty-shared/data-source';
import { type RecordGqlOperationFilter } from 'twenty-shared/types';

type TableName = string;

const ALWAYS_NULL_DELETED = {
  deletedAt: null,
};

const includesDeletedClause = (
  filter: RecordGqlOperationFilter | null | undefined,
): boolean => {
  if (!filter || typeof filter !== 'object') return false;
  const candidate = filter as Record<string, unknown>;
  if (typeof candidate.deletedAt === 'object' && candidate.deletedAt !== null)
    return true;
  if (Array.isArray(candidate.or))
    return candidate.or.some((subFilter) =>
      includesDeletedClause(subFilter as RecordGqlOperationFilter),
    );
  return false;
};

// Convex's typed db interface unions only known table names; cast to `never`
// to keep the generic dispatch readable.
const collect = async (
  ctx: {
    db: {
      query: (name: TableName) => {
        collect: () => Promise<DataSourceRecord[]>;
      };
    };
  },
  objectName: TableName,
): Promise<DataSourceRecord[]> => {
  return ctx.db.query(objectName as never).collect();
};

const fetchRecords = async (
  ctx: Parameters<typeof collect>[0],
  objectName: TableName,
  filter?: RecordGqlOperationFilter | null,
): Promise<DataSourceRecord[]> => {
  const all = await collect(ctx, objectName);
  const showDeleted = includesDeletedClause(filter ?? undefined);
  const visible = showDeleted
    ? all
    : all.filter(
        (record) => record.deletedAt === null || record.deletedAt === undefined,
      );
  const predicate = filterToPredicate(filter ?? undefined);
  return visible.filter(predicate);
};

const findMany = async (
  ctx: Parameters<typeof collect>[0],
  objectName: TableName,
  args: DataSourceFindManyArgs,
) => {
  const matched = await fetchRecords(ctx, objectName, args.filter);
  const sorted = [...matched].sort(orderByToComparator(args.orderBy ?? null));

  const offset = args.offset ?? 0;
  const startCursor = decodeCursor(args.after);
  const baseIndex = (startCursor !== null ? startCursor + 1 : 0) + offset;
  const limit =
    typeof args.first === 'number'
      ? args.first
      : typeof args.last === 'number'
        ? args.last
        : sorted.length - baseIndex;

  const slice = sorted.slice(baseIndex, baseIndex + limit);
  const startIndex = baseIndex;
  const endIndex = baseIndex + slice.length - 1;

  return {
    records: slice,
    pageInfo: {
      hasNextPage: baseIndex + slice.length < sorted.length,
      hasPreviousPage: startIndex > 0,
      startCursor: slice.length > 0 ? encodeCursor(startIndex) : null,
      endCursor: slice.length > 0 ? encodeCursor(endIndex) : null,
    },
    totalCount: matched.length,
  };
};

const findOne = async (
  ctx: Parameters<typeof collect>[0],
  objectName: TableName,
  args: DataSourceFindOneArgs,
): Promise<DataSourceRecord | null> => {
  const matched = await fetchRecords(ctx, objectName, args.filter);
  return matched[0] ?? null;
};

const lookupOne = async (
  ctx: {
    db: {
      query: (name: TableName) => {
        collect: () => Promise<DataSourceRecord[]>;
      };
    };
  },
  objectName: TableName,
  id: string,
): Promise<DataSourceRecord | undefined> => {
  const all = await collect(ctx, objectName);
  return all.find((record) => record.id === id);
};

const ok = (body: unknown): Response =>
  new Response(JSON.stringify(body), {
    headers: { 'Content-Type': 'application/json' },
  });

export const findManyAction = httpAction(async (ctx, request) => {
  const { objectName, args } = (await request.json()) as {
    objectName: string;
    args: DataSourceFindManyArgs;
  };
  return ok(await findMany(ctx as never, objectName, args));
});

export const findOneAction = httpAction(async (ctx, request) => {
  const { objectName, args } = (await request.json()) as {
    objectName: string;
    args: DataSourceFindOneArgs;
  };
  return ok(await findOne(ctx as never, objectName, args));
});

export const findDuplicatesAction = httpAction(async (_ctx, _request) => {
  return ok({
    records: [],
    pageInfo: {
      hasNextPage: false,
      hasPreviousPage: false,
      startCursor: null,
      endCursor: null,
    },
    totalCount: 0,
  });
});

export const aggregateAction = httpAction(async (ctx, request) => {
  const { objectName, args } = (await request.json()) as {
    objectName: string;
    args: { filter?: RecordGqlOperationFilter | null; fields: string[] };
  };
  const matched = await fetchRecords(ctx as never, objectName, args.filter);
  return ok(computeAggregate(matched, args.fields));
});

export const searchAction = httpAction(async (ctx, request) => {
  const { args, objectNames } = (await request.json()) as {
    args: DataSourceSearchArgs;
    // The caller supplies the candidate object table names — Convex's typed
    // db unions can't be enumerated at runtime without the schema bundle, so
    // the client side decides the search scope.
    objectNames: string[];
  };
  const sources = await Promise.all(
    objectNames.map(async (objectName) => ({
      objectName,
      objectLabelSingular: objectName,
      records: (await collect(ctx as never, objectName)).filter(
        (record) => record.deletedAt === null || record.deletedAt === undefined,
      ),
    })),
  );
  return ok(computeSearch(args, sources));
});

export const createOneAction = httpAction(async (ctx, request) => {
  const { objectName, input } = (await request.json()) as {
    objectName: string;
    input: Record<string, unknown>;
  };
  const now = new Date().toISOString();
  const record: DataSourceRecord = {
    id:
      typeof input.id === 'string' && input.id.length > 0
        ? input.id
        : crypto.randomUUID(),
    ...input,
    createdAt: typeof input.createdAt === 'string' ? input.createdAt : now,
    updatedAt: now,
    ...ALWAYS_NULL_DELETED,
  } as DataSourceRecord;
  await (ctx.db.insert as never)(objectName as never, record as never);
  return ok(record);
});

export const updateOneAction = httpAction(async (ctx, request) => {
  const { objectName, id, input } = (await request.json()) as {
    objectName: string;
    id: string;
    input: Record<string, unknown>;
  };
  const existing = await lookupOne(ctx as never, objectName, id);
  if (!existing)
    return new Response(`Not found: ${objectName}/${id}`, { status: 404 });
  const next: DataSourceRecord = {
    ...existing,
    ...input,
    id: existing.id,
    updatedAt: new Date().toISOString(),
  };
  await (ctx.db.replace as never)(
    (existing as DataSourceRecord & { _id: string })._id as never,
    next as never,
  );
  return ok(next);
});

export const deleteOneAction = httpAction(async (ctx, request) => {
  const { objectName, id } = (await request.json()) as {
    objectName: string;
    id: string;
  };
  const existing = await lookupOne(ctx as never, objectName, id);
  if (!existing)
    return new Response(`Not found: ${objectName}/${id}`, { status: 404 });
  const now = new Date().toISOString();
  const next: DataSourceRecord = {
    ...existing,
    deletedAt: now,
    updatedAt: now,
  };
  await (ctx.db.replace as never)(
    (existing as DataSourceRecord & { _id: string })._id as never,
    next as never,
  );
  return ok(next);
});

export const destroyOneAction = httpAction(async (ctx, request) => {
  const { objectName, id } = (await request.json()) as {
    objectName: string;
    id: string;
  };
  const existing = await lookupOne(ctx as never, objectName, id);
  if (!existing) return ok({ id });
  await (ctx.db.delete as never)(
    (existing as DataSourceRecord & { _id: string })._id as never,
  );
  return ok({ id });
});

export const restoreManyAction = httpAction(async (ctx, request) => {
  const { objectName, args } = (await request.json()) as {
    objectName: string;
    args: DataSourceFindOneArgs;
  };
  const matched = await fetchRecords(ctx as never, objectName, args.filter);
  const restored: Array<{ id: string }> = [];
  const now = new Date().toISOString();
  for (const record of matched) {
    if (record.deletedAt) {
      await (ctx.db.replace as never)(
        (record as DataSourceRecord & { _id: string })._id as never,
        { ...record, deletedAt: null, updatedAt: now } as never,
      );
      restored.push({ id: record.id });
    }
  }
  return ok(restored);
});
