import { defineTable } from 'convex/server';
import { v } from 'convex/values';

// Auto-generated from DataSourceBundle. Regenerate via the data-source
// schema script — see twenty-shared/data-source/utils/generateConvexSchema.
// Exported as a plain object so `schema.ts` can spread it alongside
// hand-written system tables (`systemSchema.ts`) in a single defineSchema().

export const recordTables = {
  calendarEvent: defineTable({
    id: v.string(),
    isCanceled: v.optional(v.boolean()),
    isFullDay: v.optional(v.boolean()),
    startsAt: v.optional(v.string()),
    endsAt: v.optional(v.string()),
    externalCreatedAt: v.optional(v.string()),
    externalUpdatedAt: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    location: v.optional(v.string()),
    iCalUid: v.optional(v.string()),
    conferenceSolution: v.optional(v.string()),
    conferenceLink: v.optional(v.any()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  calendarChannelEventAssociation: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    eventExternalId: v.optional(v.string()),
    recurringEventExternalId: v.optional(v.string()),
    calendarChannelId: v.optional(v.string()),
    calendarEventId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_calendarEvent_id', ['calendarEventId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  dashboard: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    title: v.optional(v.string()),
    position: v.optional(v.number()),
    pageLayoutId: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    searchVector: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  opportunity: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    name: v.optional(v.string()),
    amount: v.optional(v.any()),
    closeDate: v.optional(v.string()),
    stage: v.optional(v.string()),
    position: v.optional(v.number()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    searchVector: v.optional(v.string()),
    companyId: v.optional(v.string()),
    pointOfContactId: v.optional(v.string()),
    ownerId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_company_id', ['companyId'])
.index('by_pointOfContact_id', ['pointOfContactId'])
.index('by_owner_id', ['ownerId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  calendarChannel: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    handle: v.optional(v.string()),
    visibility: v.optional(v.string()),
    isContactAutoCreationEnabled: v.optional(v.boolean()),
    contactAutoCreationPolicy: v.optional(v.string()),
    isSyncEnabled: v.optional(v.boolean()),
    syncCursor: v.optional(v.string()),
    syncStatus: v.optional(v.string()),
    syncStage: v.optional(v.string()),
    syncStageStartedAt: v.optional(v.string()),
    syncedAt: v.optional(v.string()),
    throttleFailureCount: v.optional(v.number()),
    connectedAccountId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_connectedAccount_id', ['connectedAccountId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  messageThread: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    subject: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  messageChannel: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    visibility: v.optional(v.string()),
    handle: v.optional(v.string()),
    type: v.optional(v.string()),
    isContactAutoCreationEnabled: v.optional(v.boolean()),
    contactAutoCreationPolicy: v.optional(v.string()),
    messageFolderImportPolicy: v.optional(v.string()),
    excludeNonProfessionalEmails: v.optional(v.boolean()),
    excludeGroupEmails: v.optional(v.boolean()),
    pendingGroupEmailsAction: v.optional(v.string()),
    isSyncEnabled: v.optional(v.boolean()),
    syncCursor: v.optional(v.string()),
    syncedAt: v.optional(v.string()),
    syncStatus: v.optional(v.string()),
    syncStage: v.optional(v.string()),
    syncStageStartedAt: v.optional(v.string()),
    throttleFailureCount: v.optional(v.number()),
    throttleRetryAfter: v.optional(v.string()),
    connectedAccountId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_connectedAccount_id', ['connectedAccountId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  timelineActivity: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    happensAt: v.optional(v.string()),
    name: v.optional(v.string()),
    properties: v.optional(v.any()),
    linkedRecordCachedName: v.optional(v.string()),
    linkedRecordId: v.optional(v.string()),
    linkedObjectMetadataId: v.optional(v.string()),
    searchVector: v.optional(v.string()),
    workspaceMemberId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_workspaceMember_id', ['workspaceMemberId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  connectedAccount: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    handle: v.optional(v.string()),
    provider: v.optional(v.string()),
    accessToken: v.optional(v.string()),
    refreshToken: v.optional(v.string()),
    lastSyncHistoryId: v.optional(v.string()),
    authFailedAt: v.optional(v.string()),
    lastCredentialsRefreshedAt: v.optional(v.string()),
    handleAliases: v.optional(v.string()),
    scopes: v.optional(v.array(v.string())),
    connectionParameters: v.optional(v.any()),
    accountOwnerId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_accountOwner_id', ['accountOwnerId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  workflow: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    name: v.optional(v.string()),
    lastPublishedVersionId: v.optional(v.string()),
    statuses: v.optional(v.array(v.string())),
    position: v.optional(v.number()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    searchVector: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  surveyResult: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    score: v.optional(v.number()),
    percentageOfCompletion: v.optional(v.number()),
    participants: v.optional(v.number()),
    averageEstimatedNumberOfAtomsInTheUniverse: v.optional(v.number()),
    comments: v.optional(v.string()),
    shortNotes: v.optional(v.string()),
    files: v.optional(v.any()),
    helpedPetsId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_helpedPets_id', ['helpedPetsId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  noteTarget: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    noteId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_note_id', ['noteId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  messageParticipant: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    role: v.optional(v.string()),
    handle: v.optional(v.string()),
    displayName: v.optional(v.string()),
    messageId: v.optional(v.string()),
    personId: v.optional(v.string()),
    workspaceMemberId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_message_id', ['messageId'])
.index('by_person_id', ['personId'])
.index('by_workspaceMember_id', ['workspaceMemberId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  attachment: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    name: v.optional(v.string()),
    file: v.optional(v.any()),
    fullPath: v.optional(v.string()),
    fileCategory: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  workflowAutomatedTrigger: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    type: v.optional(v.string()),
    settings: v.optional(v.any()),
    workflowId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_workflow_id', ['workflowId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  calendarEventParticipant: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    handle: v.optional(v.string()),
    displayName: v.optional(v.string()),
    isOrganizer: v.optional(v.boolean()),
    responseStatus: v.optional(v.string()),
    calendarEventId: v.optional(v.string()),
    personId: v.optional(v.string()),
    workspaceMemberId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_calendarEvent_id', ['calendarEventId'])
.index('by_person_id', ['personId'])
.index('by_workspaceMember_id', ['workspaceMemberId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  messageChannelMessageAssociation: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    messageExternalId: v.optional(v.string()),
    messageThreadExternalId: v.optional(v.string()),
    direction: v.optional(v.string()),
    messageChannelId: v.optional(v.string()),
    messageId: v.optional(v.string()),
    messageThreadId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_message_id', ['messageId'])
.index('by_messageThread_id', ['messageThreadId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  rocket: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    helpedPetsId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_helpedPets_id', ['helpedPetsId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  workflowRun: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    name: v.optional(v.string()),
    enqueuedAt: v.optional(v.string()),
    startedAt: v.optional(v.string()),
    endedAt: v.optional(v.string()),
    status: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    state: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    workflowId: v.optional(v.string()),
    workflowVersionId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_workflow_id', ['workflowId'])
.index('by_workflowVersion_id', ['workflowVersionId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  workspaceMember: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    name: v.optional(v.any()),
    colorScheme: v.optional(v.string()),
    locale: v.optional(v.string()),
    avatarUrl: v.optional(v.string()),
    userEmail: v.optional(v.string()),
    calendarStartDay: v.optional(v.number()),
    userId: v.optional(v.string()),
    timeZone: v.optional(v.string()),
    dateFormat: v.optional(v.string()),
    timeFormat: v.optional(v.string()),
    numberFormat: v.optional(v.string()),
    searchVector: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  pet: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    name: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    species: v.optional(v.string()),
    traits: v.optional(v.array(v.string())),
    comments: v.optional(v.string()),
    age: v.optional(v.number()),
    location: v.optional(v.any()),
    vetPhone: v.optional(v.any()),
    vetEmail: v.optional(v.any()),
    birthday: v.optional(v.string()),
    isGoodWithKids: v.optional(v.boolean()),
    pictures: v.optional(v.any()),
    averageCostOfKibblePerMonth: v.optional(v.any()),
    makesOwnerThinkOf: v.optional(v.any()),
    soundSwag: v.optional(v.string()),
    bio: v.optional(v.string()),
    interestingFacts: v.optional(v.array(v.string())),
    extraData: v.optional(v.any()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  petCareAgreement: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    petId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_pet_id', ['petId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  messageChannelMessageAssociationMessageFolder: defineTable({
    id: v.string(),
    searchVector: v.optional(v.string()),
    messageFolderId: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    messageChannelMessageAssociationId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_messageChannelMessageAssociation_id', ['messageChannelMessageAssociationId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  task: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    title: v.optional(v.string()),
    bodyV2: v.optional(v.any()),
    dueAt: v.optional(v.string()),
    status: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    searchVector: v.optional(v.string()),
    assigneeId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_assignee_id', ['assigneeId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  workflowVersion: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    name: v.optional(v.string()),
    trigger: v.optional(v.any()),
    steps: v.optional(v.any()),
    status: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    workflowId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_workflow_id', ['workflowId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  person: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    name: v.optional(v.any()),
    emails: v.optional(v.any()),
    linkedinLink: v.optional(v.any()),
    xLink: v.optional(v.any()),
    jobTitle: v.optional(v.string()),
    phones: v.optional(v.any()),
    city: v.optional(v.string()),
    avatarUrl: v.optional(v.string()),
    avatarFile: v.optional(v.any()),
    position: v.optional(v.number()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    searchVector: v.optional(v.string()),
    companyId: v.optional(v.string()),
    intro: v.optional(v.string()),
    whatsapp: v.optional(v.any()),
    workPreference: v.optional(v.array(v.string())),
    performanceRating: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_company_id', ['companyId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  taskTarget: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    taskId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_task_id', ['taskId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  company: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    name: v.optional(v.string()),
    domainName: v.optional(v.any()),
    address: v.optional(v.any()),
    employees: v.optional(v.number()),
    linkedinLink: v.optional(v.any()),
    xLink: v.optional(v.any()),
    annualRecurringRevenue: v.optional(v.any()),
    idealCustomerProfile: v.optional(v.boolean()),
    position: v.optional(v.number()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    searchVector: v.optional(v.string()),
    accountOwnerId: v.optional(v.string()),
    tagline: v.optional(v.string()),
    introVideo: v.optional(v.any()),
    workPolicy: v.optional(v.array(v.string())),
    visaSponsorship: v.optional(v.boolean()),
  })
    .index('by_external_id', ['id'])
.index('by_accountOwner_id', ['accountOwnerId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  note: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    title: v.optional(v.string()),
    bodyV2: v.optional(v.any()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    searchVector: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  message: defineTable({
    id: v.string(),
    text: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    headerMessageId: v.optional(v.string()),
    subject: v.optional(v.string()),
    receivedAt: v.optional(v.string()),
    messageThreadId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_messageThread_id', ['messageThreadId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  blocklist: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    handle: v.optional(v.string()),
    workspaceMemberId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_workspaceMember_id', ['workspaceMemberId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  messageFolder: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    updatedBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    name: v.optional(v.string()),
    syncCursor: v.optional(v.string()),
    isSentFolder: v.optional(v.boolean()),
    isSynced: v.optional(v.boolean()),
    parentFolderId: v.optional(v.string()),
    externalId: v.optional(v.string()),
    pendingSyncAction: v.optional(v.string()),
    messageChannelId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  employmentHistory: defineTable({
    id: v.string(),
    createdAt: v.optional(v.string()),
    deletedAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    personId: v.optional(v.string()),
    companyId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_person_id', ['personId'])
.index('by_company_id', ['companyId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  researchTeam: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    principalInvestigator: v.optional(v.string()),
    institution: v.optional(v.string()),
    department: v.optional(v.string()),
    focusAreas: v.optional(v.array(v.string())),
    individualMode: v.optional(v.boolean()),
    website: v.optional(v.string()),
    notes: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  researcher: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    email: v.optional(v.string()),
    role: v.optional(v.string()),
    orcid: v.optional(v.string()),
    institution: v.optional(v.string()),
    status: v.optional(v.string()),
    notes: v.optional(v.string()),
    teamId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_team_id', ['teamId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  project: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    status: v.optional(v.string()),
    fundingStatus: v.optional(v.string()),
    summary: v.optional(v.string()),
    startDate: v.optional(v.string()),
    endDate: v.optional(v.string()),
    notes: v.optional(v.string()),
    teamId: v.optional(v.string()),
    leadId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_team_id', ['teamId'])
.index('by_lead_id', ['leadId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  grant: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    funder: v.optional(v.string()),
    program: v.optional(v.string()),
    status: v.optional(v.string()),
    priority: v.optional(v.string()),
    amountRequested: v.optional(v.number()),
    amountAwarded: v.optional(v.number()),
    fitScore: v.optional(v.number()),
    applicationDueDate: v.optional(v.string()),
    submittedAt: v.optional(v.string()),
    decisionAt: v.optional(v.string()),
    startDate: v.optional(v.string()),
    endDate: v.optional(v.string()),
    nextReportDue: v.optional(v.string()),
    opportunityUrl: v.optional(v.string()),
    nextAction: v.optional(v.string()),
    notes: v.optional(v.string()),
    leadId: v.optional(v.string()),
    projectId: v.optional(v.string()),
    opportunityId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_lead_id', ['leadId'])
.index('by_project_id', ['projectId'])
.index('by_opportunity_id', ['opportunityId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  grantSource: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    url: v.optional(v.string()),
    sourceType: v.optional(v.string()),
    jurisdiction: v.optional(v.string()),
    funderType: v.optional(v.string()),
    opportunityKind: v.optional(v.string()),
    topicTags: v.optional(v.array(v.string())),
    eligibilityTags: v.optional(v.array(v.string())),
    scrapeCadence: v.optional(v.string()),
    trustLevel: v.optional(v.string()),
    status: v.optional(v.string()),
    lastScrapedAt: v.optional(v.string()),
    notes: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  grantOpportunity: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    funder: v.optional(v.string()),
    program: v.optional(v.string()),
    opportunityUrl: v.optional(v.string()),
    applicationDueDate: v.optional(v.string()),
    registrationDueDate: v.optional(v.string()),
    opportunityKind: v.optional(v.string()),
    amountText: v.optional(v.string()),
    fitScore: v.optional(v.number()),
    confidence: v.optional(v.string()),
    status: v.optional(v.string()),
    eligibility: v.optional(v.string()),
    careerStage: v.optional(v.string()),
    eligibilityNotes: v.optional(v.string()),
    relevanceVerdict: v.optional(v.string()),
    relevanceReason: v.optional(v.string()),
    topicTags: v.optional(v.array(v.string())),
    description: v.optional(v.string()),
    sourceId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_source_id', ['sourceId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  grantApplication: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    organization: v.optional(v.string()),
    email: v.optional(v.string()),
    amountRequested: v.optional(v.number()),
    projectSummary: v.optional(v.string()),
    status: v.optional(v.string()),
    source: v.optional(v.string()),
    submittedAt: v.optional(v.string()),
    notes: v.optional(v.string()),
    applicantId: v.optional(v.string()),
    grantId: v.optional(v.string()),
    cycleId: v.optional(v.string()),
    projectId: v.optional(v.string()),
    opportunityId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_applicant_id', ['applicantId'])
.index('by_grant_id', ['grantId'])
.index('by_cycle_id', ['cycleId'])
.index('by_project_id', ['projectId'])
.index('by_opportunity_id', ['opportunityId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  applicationCycle: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    status: v.optional(v.string()),
    openDate: v.optional(v.string()),
    closeDate: v.optional(v.string()),
    focus: v.optional(v.string()),
    owner: v.optional(v.string()),
    description: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  milestone: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    status: v.optional(v.string()),
    dueDate: v.optional(v.string()),
    progress: v.optional(v.number()),
    notes: v.optional(v.string()),
    ownerId: v.optional(v.string()),
    projectId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_owner_id', ['ownerId'])
.index('by_project_id', ['projectId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  dataset: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    dataType: v.optional(v.string()),
    status: v.optional(v.string()),
    storageLocation: v.optional(v.string()),
    sizeGb: v.optional(v.number()),
    hasEthicsApproval: v.optional(v.boolean()),
    collectedAt: v.optional(v.string()),
    notes: v.optional(v.string()),
    projectId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_project_id', ['projectId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  manuscript: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    manuscriptType: v.optional(v.string()),
    status: v.optional(v.string()),
    targetVenue: v.optional(v.string()),
    progress: v.optional(v.number()),
    targetDate: v.optional(v.string()),
    doi: v.optional(v.string()),
    notes: v.optional(v.string()),
    leadAuthorId: v.optional(v.string()),
    projectId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_leadAuthor_id', ['leadAuthorId'])
.index('by_project_id', ['projectId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  applicationRequirement: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    category: v.optional(v.string()),
    status: v.optional(v.string()),
    dueDate: v.optional(v.string()),
    formNumber: v.optional(v.string()),
    notes: v.optional(v.string()),
    applicationId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_application_id', ['applicationId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  applicantProfile: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    fullName: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    orcid: v.optional(v.string()),
    careerStage: v.optional(v.string()),
    citizenship: v.optional(v.string()),
    residency: v.optional(v.string()),
    institution: v.optional(v.string()),
    department: v.optional(v.string()),
    discipline: v.optional(v.string()),
    keywords: v.optional(v.array(v.string())),
    addressLine1: v.optional(v.string()),
    city: v.optional(v.string()),
    province: v.optional(v.string()),
    postalCode: v.optional(v.string()),
    country: v.optional(v.string()),
    bioShort: v.optional(v.string()),
    bioLong: v.optional(v.string()),
    notes: v.optional(v.string()),
    researcherId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_researcher_id', ['researcherId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  applicationSection: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    sectionType: v.optional(v.string()),
    status: v.optional(v.string()),
    prompt: v.optional(v.string()),
    content: v.optional(v.string()),
    wordLimit: v.optional(v.number()),
    wordCount: v.optional(v.number()),
    reusedFromId: v.optional(v.string()),
    notes: v.optional(v.string()),
    applicationId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_application_id', ['applicationId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
  reusableAnswer: defineTable({
    id: v.string(),
    name: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    createdBy: v.optional(v.any()),
    deletedAt: v.optional(v.string()),
    position: v.optional(v.number()),
    searchVector: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    updatedBy: v.optional(v.any()),
    questionType: v.optional(v.string()),
    content: v.optional(v.string()),
    funder: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    wordCount: v.optional(v.number()),
    timesUsed: v.optional(v.number()),
    lastUsedAt: v.optional(v.string()),
    notes: v.optional(v.string()),
    projectId: v.optional(v.string()),
    authorId: v.optional(v.string()),
  })
    .index('by_external_id', ['id'])
.index('by_project_id', ['projectId'])
.index('by_author_id', ['authorId'])
.index('by_updatedAt', ['updatedAt'])
.index('by_createdAt', ['createdAt'])
.index('by_deletedAt', ['deletedAt']),
};
